//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopRevenueGov2.RTTIE016_SrvRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS", ConfigurationName="RTTIE016_SrvRef.RTTIE216WS_PortType")]
    public interface RTTIE216WS_PortType {
        
        // CODEGEN: Generating message contract since message part namespace (urn:com-softwareag-entirex-rpc:TIPSACCD) does not match the default value (http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS)
        [System.ServiceModel.OperationContractAttribute(Action="RTTIE216_service_RTTIE216WS_Binder_RTTIE216", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RTTIE216Response")]
        CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Response1 RTTIE216(CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RTTIE216_service_RTTIE216WS_Binder_RTTIE216", ReplyAction="*")]
        System.Threading.Tasks.Task<CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Response1> RTTIE216Async(CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
    public partial class RTTIE216 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _SMA _SMAField;
        
        private _EMI _EMIField;
        
        private _ETA _ETAField;
        
        private _EWAGNTL _EWAGNTLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public _SMA _SMA {
            get {
                return this._SMAField;
            }
            set {
                this._SMAField = value;
                this.RaisePropertyChanged("_SMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public _EMI _EMI {
            get {
                return this._EMIField;
            }
            set {
                this._EMIField = value;
                this.RaisePropertyChanged("_EMI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public _ETA _ETA {
            get {
                return this._ETAField;
            }
            set {
                this._ETAField = value;
                this.RaisePropertyChanged("_ETA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_E-WAG-NTL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public _EWAGNTL _EWAGNTL {
            get {
                return this._EWAGNTLField;
            }
            set {
                this._EWAGNTLField = value;
                this.RaisePropertyChanged("_EWAGNTL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _SMA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SYSTEM-MESSAGE-AREA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public _SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREA {
            get {
                return this._SYSTEMMESSAGEAREAField;
            }
            set {
                this._SYSTEMMESSAGEAREAField = value;
                this.RaisePropertyChanged("_SYSTEMMESSAGEAREA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_SYSTEM-MESSAGE-AREA", Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _SYSTEMMESSAGEAREA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _PROGRAMField;
        
        private System.Nullable<decimal> eRRORField;
        
        private bool eRRORFieldSpecified;
        
        private System.Nullable<decimal> lINEField;
        
        private bool lINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
                this.RaisePropertyChanged("_PROGRAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<decimal> ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORSpecified {
            get {
                return this.eRRORFieldSpecified;
            }
            set {
                this.eRRORFieldSpecified = value;
                this.RaisePropertyChanged("ERRORSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<decimal> LINE {
            get {
                return this.lINEField;
            }
            set {
                this.lINEField = value;
                this.RaisePropertyChanged("LINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LINESpecified {
            get {
                return this.lINEFieldSpecified;
            }
            set {
                this.lINEFieldSpecified = value;
                this.RaisePropertyChanged("LINESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="PERIOD-X2", Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class PERIODX2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal pERIODField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal PERIOD {
            get {
                return this.pERIODField;
            }
            set {
                this.pERIODField = value;
                this.RaisePropertyChanged("PERIOD");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_E-WAG-NTL2", Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _EWAGNTL2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aCCOUNTIDField;
        
        private PERIODX2 pERIODXField;
        
        private string fREQUENCYField;
        
        private string aDJREFNOField;
        
        private string pREPARERNAMEField;
        
        private string pREPARERPHONEField;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
                this.RaisePropertyChanged("ACCOUNTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PERIODX2 PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
                this.RaisePropertyChanged("PERIODX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
                this.RaisePropertyChanged("FREQUENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJ-REFNO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ADJREFNO {
            get {
                return this.aDJREFNOField;
            }
            set {
                this.aDJREFNOField = value;
                this.RaisePropertyChanged("ADJREFNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
                this.RaisePropertyChanged("PREPARERNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
                this.RaisePropertyChanged("PREPARERPHONE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
                this.RaisePropertyChanged("PREPARERPHONEEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
                this.RaisePropertyChanged("PREPARERIPADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PREPAREREMAIL {
            get {
                return this.pREPAREREMAILField;
            }
            set {
                this.pREPAREREMAILField = value;
                this.RaisePropertyChanged("PREPAREREMAIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
                this.RaisePropertyChanged("PREPARERTYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_ENTITY-TAX-ACCOUNTS2", Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _ENTITYTAXACCOUNTS2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fUNCTIONCODEField;
        
        private decimal aCCOUNTField;
        
        private string aCCOUNTIDField;
        
        private decimal sTARTDATEField;
        
        private decimal eNDDATEField;
        
        private string fREQUENCYField;
        
        private string bRTENTITYField;
        
        private string bRTADDRESSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
                this.RaisePropertyChanged("FUNCTIONCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal ACCOUNT {
            get {
                return this.aCCOUNTField;
            }
            set {
                this.aCCOUNTField = value;
                this.RaisePropertyChanged("ACCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
                this.RaisePropertyChanged("ACCOUNTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("START-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal STARTDATE {
            get {
                return this.sTARTDATEField;
            }
            set {
                this.sTARTDATEField = value;
                this.RaisePropertyChanged("STARTDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("END-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal ENDDATE {
            get {
                return this.eNDDATEField;
            }
            set {
                this.eNDDATEField = value;
                this.RaisePropertyChanged("ENDDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
                this.RaisePropertyChanged("FREQUENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ENTITY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string BRTENTITY {
            get {
                return this.bRTENTITYField;
            }
            set {
                this.bRTENTITYField = value;
                this.RaisePropertyChanged("BRTENTITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string BRTADDRESS {
            get {
                return this.bRTADDRESSField;
            }
            set {
                this.bRTADDRESSField = value;
                this.RaisePropertyChanged("BRTADDRESS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _ETA2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _ENTITYTAXACCOUNTS2[] _ENTITYTAXACCOUNTSsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_ENTITY-TAX-ACCOUNTSs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_ENTITY-TAX-ACCOUNTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public _ENTITYTAXACCOUNTS2[] _ENTITYTAXACCOUNTSs {
            get {
                return this._ENTITYTAXACCOUNTSsField;
            }
            set {
                this._ENTITYTAXACCOUNTSsField = value;
                this.RaisePropertyChanged("_ENTITYTAXACCOUNTSs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_ENTITY-MASTER-INFO2", Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _ENTITYMASTERINFO2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fUNCTIONCODEField;
        
        private decimal eNTITYTYPEField;
        
        private string eNTITYIDField;
        
        private string aCCTIDField;
        
        private string eNTITYNAMEField;
        
        private string aDDRESSLINEField;
        
        private string aDDRESSLINE2Field;
        
        private string aDDRESSLINE3Field;
        
        private string cITYField;
        
        private string sTATEField;
        
        private string zIPCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
                this.RaisePropertyChanged("FUNCTIONCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal ENTITYTYPE {
            get {
                return this.eNTITYTYPEField;
            }
            set {
                this.eNTITYTYPEField = value;
                this.RaisePropertyChanged("ENTITYTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
                this.RaisePropertyChanged("ENTITYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ACCTID {
            get {
                return this.aCCTIDField;
            }
            set {
                this.aCCTIDField = value;
                this.RaisePropertyChanged("ACCTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ENTITYNAME {
            get {
                return this.eNTITYNAMEField;
            }
            set {
                this.eNTITYNAMEField = value;
                this.RaisePropertyChanged("ENTITYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ADDRESSLINE {
            get {
                return this.aDDRESSLINEField;
            }
            set {
                this.aDDRESSLINEField = value;
                this.RaisePropertyChanged("ADDRESSLINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ADDRESSLINE2 {
            get {
                return this.aDDRESSLINE2Field;
            }
            set {
                this.aDDRESSLINE2Field = value;
                this.RaisePropertyChanged("ADDRESSLINE2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE-3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ADDRESSLINE3 {
            get {
                return this.aDDRESSLINE3Field;
            }
            set {
                this.aDDRESSLINE3Field = value;
                this.RaisePropertyChanged("ADDRESSLINE3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
                this.RaisePropertyChanged("CITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
                this.RaisePropertyChanged("STATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZIP-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ZIPCODE {
            get {
                return this.zIPCODEField;
            }
            set {
                this.zIPCODEField = value;
                this.RaisePropertyChanged("ZIPCODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _EMI2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _ENTITYMASTERINFO2 _ENTITYMASTERINFOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_ENTITY-MASTER-INFO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public _ENTITYMASTERINFO2 _ENTITYMASTERINFO {
            get {
                return this._ENTITYMASTERINFOField;
            }
            set {
                this._ENTITYMASTERINFOField = value;
                this.RaisePropertyChanged("_ENTITYMASTERINFO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_SYSTEM-MESSAGE-AREA2", Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _SYSTEMMESSAGEAREA2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _PROGRAMField;
        
        private decimal eRRORField;
        
        private decimal lINEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
                this.RaisePropertyChanged("_PROGRAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal LINE {
            get {
                return this.lINEField;
            }
            set {
                this.lINEField = value;
                this.RaisePropertyChanged("LINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _SMA2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _SYSTEMMESSAGEAREA2 _SYSTEMMESSAGEAREAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SYSTEM-MESSAGE-AREA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public _SYSTEMMESSAGEAREA2 _SYSTEMMESSAGEAREA {
            get {
                return this._SYSTEMMESSAGEAREAField;
            }
            set {
                this._SYSTEMMESSAGEAREAField = value;
                this.RaisePropertyChanged("_SYSTEMMESSAGEAREA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
    public partial class RTTIE216Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _SMA2 _SMAField;
        
        private _EMI2 _EMIField;
        
        private _ETA2 _ETAField;
        
        private _EWAGNTL2 _EWAGNTLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public _SMA2 _SMA {
            get {
                return this._SMAField;
            }
            set {
                this._SMAField = value;
                this.RaisePropertyChanged("_SMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public _EMI2 _EMI {
            get {
                return this._EMIField;
            }
            set {
                this._EMIField = value;
                this.RaisePropertyChanged("_EMI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public _ETA2 _ETA {
            get {
                return this._ETAField;
            }
            set {
                this._ETAField = value;
                this.RaisePropertyChanged("_ETA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_E-WAG-NTL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public _EWAGNTL2 _EWAGNTL {
            get {
                return this._EWAGNTLField;
            }
            set {
                this._EWAGNTLField = value;
                this.RaisePropertyChanged("_EWAGNTL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="PERIOD-X", Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class PERIODX : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> pERIODField;
        
        private bool pERIODFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<decimal> PERIOD {
            get {
                return this.pERIODField;
            }
            set {
                this.pERIODField = value;
                this.RaisePropertyChanged("PERIOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PERIODSpecified {
            get {
                return this.pERIODFieldSpecified;
            }
            set {
                this.pERIODFieldSpecified = value;
                this.RaisePropertyChanged("PERIODSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_E-WAG-NTL", Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _EWAGNTL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aCCOUNTIDField;
        
        private PERIODX pERIODXField;
        
        private string fREQUENCYField;
        
        private string aDJREFNOField;
        
        private string pREPARERNAMEField;
        
        private string pREPARERPHONEField;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
                this.RaisePropertyChanged("ACCOUNTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public PERIODX PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
                this.RaisePropertyChanged("PERIODX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
                this.RaisePropertyChanged("FREQUENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJ-REFNO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string ADJREFNO {
            get {
                return this.aDJREFNOField;
            }
            set {
                this.aDJREFNOField = value;
                this.RaisePropertyChanged("ADJREFNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
                this.RaisePropertyChanged("PREPARERNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
                this.RaisePropertyChanged("PREPARERPHONE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
                this.RaisePropertyChanged("PREPARERPHONEEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
                this.RaisePropertyChanged("PREPARERIPADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string PREPAREREMAIL {
            get {
                return this.pREPAREREMAILField;
            }
            set {
                this.pREPAREREMAILField = value;
                this.RaisePropertyChanged("PREPAREREMAIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
                this.RaisePropertyChanged("PREPARERTYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_ENTITY-TAX-ACCOUNTS", Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _ENTITYTAXACCOUNTS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fUNCTIONCODEField;
        
        private System.Nullable<decimal> aCCOUNTField;
        
        private bool aCCOUNTFieldSpecified;
        
        private string aCCOUNTIDField;
        
        private System.Nullable<decimal> sTARTDATEField;
        
        private bool sTARTDATEFieldSpecified;
        
        private System.Nullable<decimal> eNDDATEField;
        
        private bool eNDDATEFieldSpecified;
        
        private string fREQUENCYField;
        
        private string bRTENTITYField;
        
        private string bRTADDRESSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
                this.RaisePropertyChanged("FUNCTIONCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<decimal> ACCOUNT {
            get {
                return this.aCCOUNTField;
            }
            set {
                this.aCCOUNTField = value;
                this.RaisePropertyChanged("ACCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ACCOUNTSpecified {
            get {
                return this.aCCOUNTFieldSpecified;
            }
            set {
                this.aCCOUNTFieldSpecified = value;
                this.RaisePropertyChanged("ACCOUNTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
                this.RaisePropertyChanged("ACCOUNTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("START-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<decimal> STARTDATE {
            get {
                return this.sTARTDATEField;
            }
            set {
                this.sTARTDATEField = value;
                this.RaisePropertyChanged("STARTDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STARTDATESpecified {
            get {
                return this.sTARTDATEFieldSpecified;
            }
            set {
                this.sTARTDATEFieldSpecified = value;
                this.RaisePropertyChanged("STARTDATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("END-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<decimal> ENDDATE {
            get {
                return this.eNDDATEField;
            }
            set {
                this.eNDDATEField = value;
                this.RaisePropertyChanged("ENDDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENDDATESpecified {
            get {
                return this.eNDDATEFieldSpecified;
            }
            set {
                this.eNDDATEFieldSpecified = value;
                this.RaisePropertyChanged("ENDDATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
                this.RaisePropertyChanged("FREQUENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ENTITY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string BRTENTITY {
            get {
                return this.bRTENTITYField;
            }
            set {
                this.bRTENTITYField = value;
                this.RaisePropertyChanged("BRTENTITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string BRTADDRESS {
            get {
                return this.bRTADDRESSField;
            }
            set {
                this.bRTADDRESSField = value;
                this.RaisePropertyChanged("BRTADDRESS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _ETA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_ENTITY-TAX-ACCOUNTSs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public _ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSs {
            get {
                return this._ENTITYTAXACCOUNTSsField;
            }
            set {
                this._ENTITYTAXACCOUNTSsField = value;
                this.RaisePropertyChanged("_ENTITYTAXACCOUNTSs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_ENTITY-MASTER-INFO", Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _ENTITYMASTERINFO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fUNCTIONCODEField;
        
        private System.Nullable<decimal> eNTITYTYPEField;
        
        private bool eNTITYTYPEFieldSpecified;
        
        private string eNTITYIDField;
        
        private string aCCTIDField;
        
        private string eNTITYNAMEField;
        
        private string aDDRESSLINEField;
        
        private string aDDRESSLINE2Field;
        
        private string aDDRESSLINE3Field;
        
        private string cITYField;
        
        private string sTATEField;
        
        private string zIPCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
                this.RaisePropertyChanged("FUNCTIONCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<decimal> ENTITYTYPE {
            get {
                return this.eNTITYTYPEField;
            }
            set {
                this.eNTITYTYPEField = value;
                this.RaisePropertyChanged("ENTITYTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENTITYTYPESpecified {
            get {
                return this.eNTITYTYPEFieldSpecified;
            }
            set {
                this.eNTITYTYPEFieldSpecified = value;
                this.RaisePropertyChanged("ENTITYTYPESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
                this.RaisePropertyChanged("ENTITYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string ACCTID {
            get {
                return this.aCCTIDField;
            }
            set {
                this.aCCTIDField = value;
                this.RaisePropertyChanged("ACCTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string ENTITYNAME {
            get {
                return this.eNTITYNAMEField;
            }
            set {
                this.eNTITYNAMEField = value;
                this.RaisePropertyChanged("ENTITYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string ADDRESSLINE {
            get {
                return this.aDDRESSLINEField;
            }
            set {
                this.aDDRESSLINEField = value;
                this.RaisePropertyChanged("ADDRESSLINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string ADDRESSLINE2 {
            get {
                return this.aDDRESSLINE2Field;
            }
            set {
                this.aDDRESSLINE2Field = value;
                this.RaisePropertyChanged("ADDRESSLINE2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE-3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string ADDRESSLINE3 {
            get {
                return this.aDDRESSLINE3Field;
            }
            set {
                this.aDDRESSLINE3Field = value;
                this.RaisePropertyChanged("ADDRESSLINE3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
                this.RaisePropertyChanged("CITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
                this.RaisePropertyChanged("STATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZIP-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string ZIPCODE {
            get {
                return this.zIPCODEField;
            }
            set {
                this.zIPCODEField = value;
                this.RaisePropertyChanged("ZIPCODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS")]
    public partial class _EMI : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _ENTITYMASTERINFO _ENTITYMASTERINFOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_ENTITY-MASTER-INFO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public _ENTITYMASTERINFO _ENTITYMASTERINFO {
            get {
                return this._ENTITYMASTERINFOField;
            }
            set {
                this._ENTITYMASTERINFOField = value;
                this.RaisePropertyChanged("_ENTITYMASTERINFO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RTTIE216", WrapperNamespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS", IsWrapped=true)]
    public partial class RTTIE216Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
        public CopRevenueGov2.RTTIE016_SrvRef.RTTIE216 RTTIE216;
        
        public RTTIE216Request() {
        }
        
        public RTTIE216Request(CopRevenueGov2.RTTIE016_SrvRef.RTTIE216 RTTIE216) {
            this.RTTIE216 = RTTIE216;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RTTIE216Response", WrapperNamespace="http://ISDEV.city.phila.local/RTTIE216.service:RTTIE216WS", IsWrapped=true)]
    public partial class RTTIE216Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
        public CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Response RTTIE216Response;
        
        public RTTIE216Response1() {
        }
        
        public RTTIE216Response1(CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Response RTTIE216Response) {
            this.RTTIE216Response = RTTIE216Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RTTIE216WS_PortTypeChannel : CopRevenueGov2.RTTIE016_SrvRef.RTTIE216WS_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RTTIE216WS_PortTypeClient : System.ServiceModel.ClientBase<CopRevenueGov2.RTTIE016_SrvRef.RTTIE216WS_PortType>, CopRevenueGov2.RTTIE016_SrvRef.RTTIE216WS_PortType {
        
        public RTTIE216WS_PortTypeClient() {
        }
        
        public RTTIE216WS_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RTTIE216WS_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RTTIE216WS_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RTTIE216WS_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Response1 CopRevenueGov2.RTTIE016_SrvRef.RTTIE216WS_PortType.RTTIE216(CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Request request) {
            return base.Channel.RTTIE216(request);
        }
        
        public CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Response RTTIE216(CopRevenueGov2.RTTIE016_SrvRef.RTTIE216 RTTIE2161) {
            CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Request inValue = new CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Request();
            inValue.RTTIE216 = RTTIE2161;
            CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Response1 retVal = ((CopRevenueGov2.RTTIE016_SrvRef.RTTIE216WS_PortType)(this)).RTTIE216(inValue);
            return retVal.RTTIE216Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Response1> CopRevenueGov2.RTTIE016_SrvRef.RTTIE216WS_PortType.RTTIE216Async(CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Request request) {
            return base.Channel.RTTIE216Async(request);
        }
        
        public System.Threading.Tasks.Task<CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Response1> RTTIE216Async(CopRevenueGov2.RTTIE016_SrvRef.RTTIE216 RTTIE216) {
            CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Request inValue = new CopRevenueGov2.RTTIE016_SrvRef.RTTIE216Request();
            inValue.RTTIE216 = RTTIE216;
            return ((CopRevenueGov2.RTTIE016_SrvRef.RTTIE216WS_PortType)(this)).RTTIE216Async(inValue);
        }
    }
}
