//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopRevenueGov2.RTTIE229_SrvRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE229.service:RTTIE229WS", ConfigurationName="RTTIE229_SrvRef.RTTIE229WS_PortType")]
    public interface RTTIE229WS_PortType {
        
        // CODEGEN: Generating message contract since message part namespace (urn:com-softwareag-entirex-rpc:TIPSACCD) does not match the default value (http://ISDEV.city.phila.local/RTTIE229.service:RTTIE229WS)
        [System.ServiceModel.OperationContractAttribute(Action="RTTIE229_service_RTTIE229WS_Binder_RTTIE229", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RTTIE229Response")]
        CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Response1 RTTIE229(CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RTTIE229_service_RTTIE229WS_Binder_RTTIE229", ReplyAction="*")]
        System.Threading.Tasks.Task<CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Response1> RTTIE229Async(CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
    public partial class RTTIE229 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _SMA _SMAField;
        
        private _ELIQ _ELIQField;
        
        private _EAMT _EAMTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public _SMA _SMA {
            get {
                return this._SMAField;
            }
            set {
                this._SMAField = value;
                this.RaisePropertyChanged("_SMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_E-LIQ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public _ELIQ _ELIQ {
            get {
                return this._ELIQField;
            }
            set {
                this._ELIQField = value;
                this.RaisePropertyChanged("_ELIQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_E-AMT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public _EAMT _EAMT {
            get {
                return this._EAMTField;
            }
            set {
                this._EAMTField = value;
                this.RaisePropertyChanged("_EAMT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE229.service:RTTIE229WS")]
    public partial class _SMA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _PROGRAMField;
        
        private System.Nullable<decimal> sYSTEMERRORField;
        
        private bool sYSTEMERRORFieldSpecified;
        
        private System.Nullable<decimal> eRRORLINEField;
        
        private bool eRRORLINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
                this.RaisePropertyChanged("_PROGRAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SYSTEM-ERROR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<decimal> SYSTEMERROR {
            get {
                return this.sYSTEMERRORField;
            }
            set {
                this.sYSTEMERRORField = value;
                this.RaisePropertyChanged("SYSTEMERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SYSTEMERRORSpecified {
            get {
                return this.sYSTEMERRORFieldSpecified;
            }
            set {
                this.sYSTEMERRORFieldSpecified = value;
                this.RaisePropertyChanged("SYSTEMERRORSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERROR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<decimal> ERRORLINE {
            get {
                return this.eRRORLINEField;
            }
            set {
                this.eRRORLINEField = value;
                this.RaisePropertyChanged("ERRORLINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORLINESpecified {
            get {
                return this.eRRORLINEFieldSpecified;
            }
            set {
                this.eRRORLINEFieldSpecified = value;
                this.RaisePropertyChanged("ERRORLINESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_E-AMT2", Namespace="http://ISDEV.city.phila.local/RTTIE229.service:RTTIE229WS")]
    public partial class _EAMT2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tOTALGROSSXField;
        
        private string fOODEXCLUSIONXField;
        
        private string oTHEREXCLUSIONXField;
        
        private string tOTALEXCLUSIONXField;
        
        private string tAXABLEXField;
        
        private string tOTALTAXXField;
        
        private string tAXPAIDXField;
        
        private string nETTAXDUEXField;
        
        private string tAXOVERPAIDXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-GROSS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TOTALGROSSX {
            get {
                return this.tOTALGROSSXField;
            }
            set {
                this.tOTALGROSSXField = value;
                this.RaisePropertyChanged("TOTALGROSSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FOOD-EXCLUSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FOODEXCLUSIONX {
            get {
                return this.fOODEXCLUSIONXField;
            }
            set {
                this.fOODEXCLUSIONXField = value;
                this.RaisePropertyChanged("FOODEXCLUSIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OTHER-EXCLUSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OTHEREXCLUSIONX {
            get {
                return this.oTHEREXCLUSIONXField;
            }
            set {
                this.oTHEREXCLUSIONXField = value;
                this.RaisePropertyChanged("OTHEREXCLUSIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-EXCLUSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TOTALEXCLUSIONX {
            get {
                return this.tOTALEXCLUSIONXField;
            }
            set {
                this.tOTALEXCLUSIONXField = value;
                this.RaisePropertyChanged("TOTALEXCLUSIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAXABLE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TAXABLEX {
            get {
                return this.tAXABLEXField;
            }
            set {
                this.tAXABLEXField = value;
                this.RaisePropertyChanged("TAXABLEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-TAX-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TOTALTAXX {
            get {
                return this.tOTALTAXXField;
            }
            set {
                this.tOTALTAXXField = value;
                this.RaisePropertyChanged("TOTALTAXX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-PAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TAXPAIDX {
            get {
                return this.tAXPAIDXField;
            }
            set {
                this.tAXPAIDXField = value;
                this.RaisePropertyChanged("TAXPAIDX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string NETTAXDUEX {
            get {
                return this.nETTAXDUEXField;
            }
            set {
                this.nETTAXDUEXField = value;
                this.RaisePropertyChanged("NETTAXDUEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-OVERPAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string TAXOVERPAIDX {
            get {
                return this.tAXOVERPAIDXField;
            }
            set {
                this.tAXOVERPAIDXField = value;
                this.RaisePropertyChanged("TAXOVERPAIDX");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_E-LIQ2", Namespace="http://ISDEV.city.phila.local/RTTIE229.service:RTTIE229WS")]
    public partial class _ELIQ2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string vERSIONXField;
        
        private string rETURNSTATUSField;
        
        private string lASTUPDATEDATEXField;
        
        private string uSERIDField;
        
        private string rECORDINGDATEXField;
        
        private string sEQUENCENUMField;
        
        private string aDJUSTMENTREFERENCENUMField;
        
        private string rATEField;
        
        private string pREPARERNAMEField;
        
        private decimal pREPARERPHONEField;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILADDRESSField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
                this.RaisePropertyChanged("ACCOUNTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
                this.RaisePropertyChanged("PERIODX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VERSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string VERSIONX {
            get {
                return this.vERSIONXField;
            }
            set {
                this.vERSIONXField = value;
                this.RaisePropertyChanged("VERSIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RETURN-STATUS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string RETURNSTATUS {
            get {
                return this.rETURNSTATUSField;
            }
            set {
                this.rETURNSTATUSField = value;
                this.RaisePropertyChanged("RETURNSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LAST-UPDATE-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LASTUPDATEDATEX {
            get {
                return this.lASTUPDATEDATEXField;
            }
            set {
                this.lASTUPDATEDATEXField = value;
                this.RaisePropertyChanged("LASTUPDATEDATEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
                this.RaisePropertyChanged("USERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RECORDING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string RECORDINGDATEX {
            get {
                return this.rECORDINGDATEXField;
            }
            set {
                this.rECORDINGDATEXField = value;
                this.RaisePropertyChanged("RECORDINGDATEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SEQUENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SEQUENCENUM {
            get {
                return this.sEQUENCENUMField;
            }
            set {
                this.sEQUENCENUMField = value;
                this.RaisePropertyChanged("SEQUENCENUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJUSTMENT-REFERENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ADJUSTMENTREFERENCENUM {
            get {
                return this.aDJUSTMENTREFERENCENUMField;
            }
            set {
                this.aDJUSTMENTREFERENCENUMField = value;
                this.RaisePropertyChanged("ADJUSTMENTREFERENCENUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string RATE {
            get {
                return this.rATEField;
            }
            set {
                this.rATEField = value;
                this.RaisePropertyChanged("RATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
                this.RaisePropertyChanged("PREPARERNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
                this.RaisePropertyChanged("PREPARERPHONE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
                this.RaisePropertyChanged("PREPARERPHONEEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
                this.RaisePropertyChanged("PREPARERIPADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string PREPAREREMAILADDRESS {
            get {
                return this.pREPAREREMAILADDRESSField;
            }
            set {
                this.pREPAREREMAILADDRESSField = value;
                this.RaisePropertyChanged("PREPAREREMAILADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
                this.RaisePropertyChanged("PREPARERTYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE229.service:RTTIE229WS")]
    public partial class _SMA2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _PROGRAMField;
        
        private decimal sYSTEMERRORField;
        
        private decimal eRRORLINEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
                this.RaisePropertyChanged("_PROGRAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SYSTEM-ERROR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal SYSTEMERROR {
            get {
                return this.sYSTEMERRORField;
            }
            set {
                this.sYSTEMERRORField = value;
                this.RaisePropertyChanged("SYSTEMERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERROR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal ERRORLINE {
            get {
                return this.eRRORLINEField;
            }
            set {
                this.eRRORLINEField = value;
                this.RaisePropertyChanged("ERRORLINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
    public partial class RTTIE229Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _SMA2 _SMAField;
        
        private _ELIQ2 _ELIQField;
        
        private _EAMT2 _EAMTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public _SMA2 _SMA {
            get {
                return this._SMAField;
            }
            set {
                this._SMAField = value;
                this.RaisePropertyChanged("_SMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_E-LIQ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public _ELIQ2 _ELIQ {
            get {
                return this._ELIQField;
            }
            set {
                this._ELIQField = value;
                this.RaisePropertyChanged("_ELIQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_E-AMT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public _EAMT2 _EAMT {
            get {
                return this._EAMTField;
            }
            set {
                this._EAMTField = value;
                this.RaisePropertyChanged("_EAMT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_E-AMT", Namespace="http://ISDEV.city.phila.local/RTTIE229.service:RTTIE229WS")]
    public partial class _EAMT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tOTALGROSSXField;
        
        private string fOODEXCLUSIONXField;
        
        private string oTHEREXCLUSIONXField;
        
        private string tOTALEXCLUSIONXField;
        
        private string tAXABLEXField;
        
        private string tOTALTAXXField;
        
        private string tAXPAIDXField;
        
        private string nETTAXDUEXField;
        
        private string tAXOVERPAIDXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-GROSS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string TOTALGROSSX {
            get {
                return this.tOTALGROSSXField;
            }
            set {
                this.tOTALGROSSXField = value;
                this.RaisePropertyChanged("TOTALGROSSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FOOD-EXCLUSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string FOODEXCLUSIONX {
            get {
                return this.fOODEXCLUSIONXField;
            }
            set {
                this.fOODEXCLUSIONXField = value;
                this.RaisePropertyChanged("FOODEXCLUSIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OTHER-EXCLUSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string OTHEREXCLUSIONX {
            get {
                return this.oTHEREXCLUSIONXField;
            }
            set {
                this.oTHEREXCLUSIONXField = value;
                this.RaisePropertyChanged("OTHEREXCLUSIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-EXCLUSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string TOTALEXCLUSIONX {
            get {
                return this.tOTALEXCLUSIONXField;
            }
            set {
                this.tOTALEXCLUSIONXField = value;
                this.RaisePropertyChanged("TOTALEXCLUSIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAXABLE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string TAXABLEX {
            get {
                return this.tAXABLEXField;
            }
            set {
                this.tAXABLEXField = value;
                this.RaisePropertyChanged("TAXABLEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-TAX-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string TOTALTAXX {
            get {
                return this.tOTALTAXXField;
            }
            set {
                this.tOTALTAXXField = value;
                this.RaisePropertyChanged("TOTALTAXX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-PAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string TAXPAIDX {
            get {
                return this.tAXPAIDXField;
            }
            set {
                this.tAXPAIDXField = value;
                this.RaisePropertyChanged("TAXPAIDX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string NETTAXDUEX {
            get {
                return this.nETTAXDUEXField;
            }
            set {
                this.nETTAXDUEXField = value;
                this.RaisePropertyChanged("NETTAXDUEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-OVERPAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string TAXOVERPAIDX {
            get {
                return this.tAXOVERPAIDXField;
            }
            set {
                this.tAXOVERPAIDXField = value;
                this.RaisePropertyChanged("TAXOVERPAIDX");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_E-LIQ", Namespace="http://ISDEV.city.phila.local/RTTIE229.service:RTTIE229WS")]
    public partial class _ELIQ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string vERSIONXField;
        
        private string rETURNSTATUSField;
        
        private string lASTUPDATEDATEXField;
        
        private string uSERIDField;
        
        private string rECORDINGDATEXField;
        
        private string sEQUENCENUMField;
        
        private string aDJUSTMENTREFERENCENUMField;
        
        private string rATEField;
        
        private string pREPARERNAMEField;
        
        private System.Nullable<decimal> pREPARERPHONEField;
        
        private bool pREPARERPHONEFieldSpecified;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILADDRESSField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
                this.RaisePropertyChanged("ACCOUNTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
                this.RaisePropertyChanged("PERIODX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VERSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string VERSIONX {
            get {
                return this.vERSIONXField;
            }
            set {
                this.vERSIONXField = value;
                this.RaisePropertyChanged("VERSIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RETURN-STATUS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string RETURNSTATUS {
            get {
                return this.rETURNSTATUSField;
            }
            set {
                this.rETURNSTATUSField = value;
                this.RaisePropertyChanged("RETURNSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LAST-UPDATE-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string LASTUPDATEDATEX {
            get {
                return this.lASTUPDATEDATEXField;
            }
            set {
                this.lASTUPDATEDATEXField = value;
                this.RaisePropertyChanged("LASTUPDATEDATEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
                this.RaisePropertyChanged("USERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RECORDING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string RECORDINGDATEX {
            get {
                return this.rECORDINGDATEXField;
            }
            set {
                this.rECORDINGDATEXField = value;
                this.RaisePropertyChanged("RECORDINGDATEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SEQUENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string SEQUENCENUM {
            get {
                return this.sEQUENCENUMField;
            }
            set {
                this.sEQUENCENUMField = value;
                this.RaisePropertyChanged("SEQUENCENUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJUSTMENT-REFERENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string ADJUSTMENTREFERENCENUM {
            get {
                return this.aDJUSTMENTREFERENCENUMField;
            }
            set {
                this.aDJUSTMENTREFERENCENUMField = value;
                this.RaisePropertyChanged("ADJUSTMENTREFERENCENUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string RATE {
            get {
                return this.rATEField;
            }
            set {
                this.rATEField = value;
                this.RaisePropertyChanged("RATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
                this.RaisePropertyChanged("PREPARERNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public System.Nullable<decimal> PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
                this.RaisePropertyChanged("PREPARERPHONE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PREPARERPHONESpecified {
            get {
                return this.pREPARERPHONEFieldSpecified;
            }
            set {
                this.pREPARERPHONEFieldSpecified = value;
                this.RaisePropertyChanged("PREPARERPHONESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
                this.RaisePropertyChanged("PREPARERPHONEEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
                this.RaisePropertyChanged("PREPARERIPADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string PREPAREREMAILADDRESS {
            get {
                return this.pREPAREREMAILADDRESSField;
            }
            set {
                this.pREPAREREMAILADDRESSField = value;
                this.RaisePropertyChanged("PREPAREREMAILADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
                this.RaisePropertyChanged("PREPARERTYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RTTIE229", WrapperNamespace="http://ISDEV.city.phila.local/RTTIE229.service:RTTIE229WS", IsWrapped=true)]
    public partial class RTTIE229Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
        public CopRevenueGov2.RTTIE229_SrvRef.RTTIE229 RTTIE229;
        
        public RTTIE229Request() {
        }
        
        public RTTIE229Request(CopRevenueGov2.RTTIE229_SrvRef.RTTIE229 RTTIE229) {
            this.RTTIE229 = RTTIE229;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RTTIE229Response", WrapperNamespace="http://ISDEV.city.phila.local/RTTIE229.service:RTTIE229WS", IsWrapped=true)]
    public partial class RTTIE229Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
        public CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Response RTTIE229Response;
        
        public RTTIE229Response1() {
        }
        
        public RTTIE229Response1(CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Response RTTIE229Response) {
            this.RTTIE229Response = RTTIE229Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RTTIE229WS_PortTypeChannel : CopRevenueGov2.RTTIE229_SrvRef.RTTIE229WS_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RTTIE229WS_PortTypeClient : System.ServiceModel.ClientBase<CopRevenueGov2.RTTIE229_SrvRef.RTTIE229WS_PortType>, CopRevenueGov2.RTTIE229_SrvRef.RTTIE229WS_PortType {
        
        public RTTIE229WS_PortTypeClient() {
        }
        
        public RTTIE229WS_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RTTIE229WS_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RTTIE229WS_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RTTIE229WS_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Response1 CopRevenueGov2.RTTIE229_SrvRef.RTTIE229WS_PortType.RTTIE229(CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Request request) {
            return base.Channel.RTTIE229(request);
        }
        
        public CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Response RTTIE229(CopRevenueGov2.RTTIE229_SrvRef.RTTIE229 RTTIE2291) {
            CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Request inValue = new CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Request();
            inValue.RTTIE229 = RTTIE2291;
            CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Response1 retVal = ((CopRevenueGov2.RTTIE229_SrvRef.RTTIE229WS_PortType)(this)).RTTIE229(inValue);
            return retVal.RTTIE229Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Response1> CopRevenueGov2.RTTIE229_SrvRef.RTTIE229WS_PortType.RTTIE229Async(CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Request request) {
            return base.Channel.RTTIE229Async(request);
        }
        
        public System.Threading.Tasks.Task<CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Response1> RTTIE229Async(CopRevenueGov2.RTTIE229_SrvRef.RTTIE229 RTTIE229) {
            CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Request inValue = new CopRevenueGov2.RTTIE229_SrvRef.RTTIE229Request();
            inValue.RTTIE229 = RTTIE229;
            return ((CopRevenueGov2.RTTIE229_SrvRef.RTTIE229WS_PortType)(this)).RTTIE229Async(inValue);
        }
    }
}
