//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopRevenueGov2.RTTIE227_Srvref {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE227.service:RTTIE227WS", ConfigurationName="RTTIE227_Srvref.RTTIE227WS_PortType")]
    public interface RTTIE227WS_PortType {
        
        // CODEGEN: Generating message contract since message part namespace (urn:com-softwareag-entirex-rpc:TIPSACCD) does not match the default value (http://ISDEV.city.phila.local/RTTIE227.service:RTTIE227WS)
        [System.ServiceModel.OperationContractAttribute(Action="RTTIE227_service_RTTIE227WS_Binder_RTTIE227", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RTTIE227Response")]
        CopRevenueGov2.RTTIE227_Srvref.RTTIE227Response1 RTTIE227(CopRevenueGov2.RTTIE227_Srvref.RTTIE227Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RTTIE227_service_RTTIE227WS_Binder_RTTIE227", ReplyAction="*")]
        System.Threading.Tasks.Task<CopRevenueGov2.RTTIE227_Srvref.RTTIE227Response1> RTTIE227Async(CopRevenueGov2.RTTIE227_Srvref.RTTIE227Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
    public partial class RTTIE227 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _SMA _SMAField;
        
        private _EWAG _EWAGField;
        
        private _EAMT _EAMTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public _SMA _SMA {
            get {
                return this._SMAField;
            }
            set {
                this._SMAField = value;
                this.RaisePropertyChanged("_SMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_E-WAG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public _EWAG _EWAG {
            get {
                return this._EWAGField;
            }
            set {
                this._EWAGField = value;
                this.RaisePropertyChanged("_EWAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_E-AMT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public _EAMT _EAMT {
            get {
                return this._EAMTField;
            }
            set {
                this._EAMTField = value;
                this.RaisePropertyChanged("_EAMT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE227.service:RTTIE227WS")]
    public partial class _SMA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _PROGRAMField;
        
        private string sYSTEMERRORField;
        
        private string eRRORLINEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
                this.RaisePropertyChanged("_PROGRAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SYSTEM-ERROR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string SYSTEMERROR {
            get {
                return this.sYSTEMERRORField;
            }
            set {
                this.sYSTEMERRORField = value;
                this.RaisePropertyChanged("SYSTEMERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERROR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string ERRORLINE {
            get {
                return this.eRRORLINEField;
            }
            set {
                this.eRRORLINEField = value;
                this.RaisePropertyChanged("ERRORLINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_E-AMT2", Namespace="http://ISDEV.city.phila.local/RTTIE227.service:RTTIE227WS")]
    public partial class _EAMT2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gROSSCOMPENSATIONXField;
        
        private string nONTAXABLECOMPXField;
        
        private string nETCOMPENSATIONXField;
        
        private string rESIDENTPAYROLLAXField;
        
        private string rESIDENTTAXDUEAXField;
        
        private string rESIDENTPAYROLLBXField;
        
        private string rESIDENTTAXDUEBXField;
        
        private string nONRESPAYROLLAXField;
        
        private string nONRESTAXDUEAXField;
        
        private string nONRESPAYROLLBXField;
        
        private string nONRESTAXDUEBXField;
        
        private string tOTALGROSSTAXDUEXField;
        
        private string tAXPAIDXField;
        
        private string tAXDUEXField;
        
        private string tAXOVERPAIDXField;
        
        private string pOSTINGDATEXField;
        
        private string fILINGDATEXField;
        
        private string uSERIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GROSS-COMPENSATION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string GROSSCOMPENSATIONX {
            get {
                return this.gROSSCOMPENSATIONXField;
            }
            set {
                this.gROSSCOMPENSATIONXField = value;
                this.RaisePropertyChanged("GROSSCOMPENSATIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-TAXABLE-COMP-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NONTAXABLECOMPX {
            get {
                return this.nONTAXABLECOMPXField;
            }
            set {
                this.nONTAXABLECOMPXField = value;
                this.RaisePropertyChanged("NONTAXABLECOMPX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-COMPENSATION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NETCOMPENSATIONX {
            get {
                return this.nETCOMPENSATIONXField;
            }
            set {
                this.nETCOMPENSATIONXField = value;
                this.RaisePropertyChanged("NETCOMPENSATIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-PAYROLL-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string RESIDENTPAYROLLAX {
            get {
                return this.rESIDENTPAYROLLAXField;
            }
            set {
                this.rESIDENTPAYROLLAXField = value;
                this.RaisePropertyChanged("RESIDENTPAYROLLAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-TAX-DUE-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string RESIDENTTAXDUEAX {
            get {
                return this.rESIDENTTAXDUEAXField;
            }
            set {
                this.rESIDENTTAXDUEAXField = value;
                this.RaisePropertyChanged("RESIDENTTAXDUEAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-PAYROLL-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string RESIDENTPAYROLLBX {
            get {
                return this.rESIDENTPAYROLLBXField;
            }
            set {
                this.rESIDENTPAYROLLBXField = value;
                this.RaisePropertyChanged("RESIDENTPAYROLLBX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-TAX-DUE-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string RESIDENTTAXDUEBX {
            get {
                return this.rESIDENTTAXDUEBXField;
            }
            set {
                this.rESIDENTTAXDUEBXField = value;
                this.RaisePropertyChanged("RESIDENTTAXDUEBX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-PAYROLL-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string NONRESPAYROLLAX {
            get {
                return this.nONRESPAYROLLAXField;
            }
            set {
                this.nONRESPAYROLLAXField = value;
                this.RaisePropertyChanged("NONRESPAYROLLAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-TAX-DUE-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string NONRESTAXDUEAX {
            get {
                return this.nONRESTAXDUEAXField;
            }
            set {
                this.nONRESTAXDUEAXField = value;
                this.RaisePropertyChanged("NONRESTAXDUEAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-PAYROLL-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string NONRESPAYROLLBX {
            get {
                return this.nONRESPAYROLLBXField;
            }
            set {
                this.nONRESPAYROLLBXField = value;
                this.RaisePropertyChanged("NONRESPAYROLLBX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-TAX-DUE-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string NONRESTAXDUEBX {
            get {
                return this.nONRESTAXDUEBXField;
            }
            set {
                this.nONRESTAXDUEBXField = value;
                this.RaisePropertyChanged("NONRESTAXDUEBX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-GROSS-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string TOTALGROSSTAXDUEX {
            get {
                return this.tOTALGROSSTAXDUEXField;
            }
            set {
                this.tOTALGROSSTAXDUEXField = value;
                this.RaisePropertyChanged("TOTALGROSSTAXDUEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-PAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string TAXPAIDX {
            get {
                return this.tAXPAIDXField;
            }
            set {
                this.tAXPAIDXField = value;
                this.RaisePropertyChanged("TAXPAIDX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string TAXDUEX {
            get {
                return this.tAXDUEXField;
            }
            set {
                this.tAXDUEXField = value;
                this.RaisePropertyChanged("TAXDUEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-OVERPAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string TAXOVERPAIDX {
            get {
                return this.tAXOVERPAIDXField;
            }
            set {
                this.tAXOVERPAIDXField = value;
                this.RaisePropertyChanged("TAXOVERPAIDX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POSTING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string POSTINGDATEX {
            get {
                return this.pOSTINGDATEXField;
            }
            set {
                this.pOSTINGDATEXField = value;
                this.RaisePropertyChanged("POSTINGDATEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FILING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string FILINGDATEX {
            get {
                return this.fILINGDATEXField;
            }
            set {
                this.fILINGDATEXField = value;
                this.RaisePropertyChanged("FILINGDATEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
                this.RaisePropertyChanged("USERID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_E-WAG2", Namespace="http://ISDEV.city.phila.local/RTTIE227.service:RTTIE227WS")]
    public partial class _EWAG2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string vERSIONXField;
        
        private string dOCUMENTCONTROLXField;
        
        private string aDJREFNOField;
        
        private string fEDERALIDNUMBERField;
        
        private string rETURNSTATUSField;
        
        private string sEQUENCENUMField;
        
        private string lASTUPDATEDATEXField;
        
        private string nUMBEROFRESIDENTSXField;
        
        private string nUMBEROFNONRESIDENTSXField;
        
        private string pHILAEMPLOYEESXField;
        
        private string tOTALEMPLOYEESXField;
        
        private string rESRATEAField;
        
        private string rESRATEBField;
        
        private string nONRATEAField;
        
        private string nONRATEBField;
        
        private string fREQUENCYField;
        
        private string dUEDATEField;
        
        private string pREPARERNAMEField;
        
        private string pREPARERPHONEField;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILADDRESSField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
                this.RaisePropertyChanged("ACCOUNTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
                this.RaisePropertyChanged("PERIODX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VERSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string VERSIONX {
            get {
                return this.vERSIONXField;
            }
            set {
                this.vERSIONXField = value;
                this.RaisePropertyChanged("VERSIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DOCUMENT-CONTROL-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DOCUMENTCONTROLX {
            get {
                return this.dOCUMENTCONTROLXField;
            }
            set {
                this.dOCUMENTCONTROLXField = value;
                this.RaisePropertyChanged("DOCUMENTCONTROLX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJ-REFNO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ADJREFNO {
            get {
                return this.aDJREFNOField;
            }
            set {
                this.aDJREFNOField = value;
                this.RaisePropertyChanged("ADJREFNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FEDERAL-ID-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FEDERALIDNUMBER {
            get {
                return this.fEDERALIDNUMBERField;
            }
            set {
                this.fEDERALIDNUMBERField = value;
                this.RaisePropertyChanged("FEDERALIDNUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RETURN-STATUS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string RETURNSTATUS {
            get {
                return this.rETURNSTATUSField;
            }
            set {
                this.rETURNSTATUSField = value;
                this.RaisePropertyChanged("RETURNSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SEQUENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SEQUENCENUM {
            get {
                return this.sEQUENCENUMField;
            }
            set {
                this.sEQUENCENUMField = value;
                this.RaisePropertyChanged("SEQUENCENUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LAST-UPDATE-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string LASTUPDATEDATEX {
            get {
                return this.lASTUPDATEDATEXField;
            }
            set {
                this.lASTUPDATEDATEXField = value;
                this.RaisePropertyChanged("LASTUPDATEDATEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NUMBER-OF-RESIDENTS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string NUMBEROFRESIDENTSX {
            get {
                return this.nUMBEROFRESIDENTSXField;
            }
            set {
                this.nUMBEROFRESIDENTSXField = value;
                this.RaisePropertyChanged("NUMBEROFRESIDENTSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NUMBER-OF-NON-RESIDENTS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string NUMBEROFNONRESIDENTSX {
            get {
                return this.nUMBEROFNONRESIDENTSXField;
            }
            set {
                this.nUMBEROFNONRESIDENTSXField = value;
                this.RaisePropertyChanged("NUMBEROFNONRESIDENTSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PHILA-EMPLOYEES-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string PHILAEMPLOYEESX {
            get {
                return this.pHILAEMPLOYEESXField;
            }
            set {
                this.pHILAEMPLOYEESXField = value;
                this.RaisePropertyChanged("PHILAEMPLOYEESX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-EMPLOYEES-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string TOTALEMPLOYEESX {
            get {
                return this.tOTALEMPLOYEESXField;
            }
            set {
                this.tOTALEMPLOYEESXField = value;
                this.RaisePropertyChanged("TOTALEMPLOYEESX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-RATE-A", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string RESRATEA {
            get {
                return this.rESRATEAField;
            }
            set {
                this.rESRATEAField = value;
                this.RaisePropertyChanged("RESRATEA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-RATE-B", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string RESRATEB {
            get {
                return this.rESRATEBField;
            }
            set {
                this.rESRATEBField = value;
                this.RaisePropertyChanged("RESRATEB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RATE-A", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string NONRATEA {
            get {
                return this.nONRATEAField;
            }
            set {
                this.nONRATEAField = value;
                this.RaisePropertyChanged("NONRATEA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RATE-B", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string NONRATEB {
            get {
                return this.nONRATEBField;
            }
            set {
                this.nONRATEBField = value;
                this.RaisePropertyChanged("NONRATEB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
                this.RaisePropertyChanged("FREQUENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DUE-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string DUEDATE {
            get {
                return this.dUEDATEField;
            }
            set {
                this.dUEDATEField = value;
                this.RaisePropertyChanged("DUEDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
                this.RaisePropertyChanged("PREPARERNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
                this.RaisePropertyChanged("PREPARERPHONE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
                this.RaisePropertyChanged("PREPARERPHONEEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
                this.RaisePropertyChanged("PREPARERIPADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string PREPAREREMAILADDRESS {
            get {
                return this.pREPAREREMAILADDRESSField;
            }
            set {
                this.pREPAREREMAILADDRESSField = value;
                this.RaisePropertyChanged("PREPAREREMAILADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
                this.RaisePropertyChanged("PREPARERTYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE227.service:RTTIE227WS")]
    public partial class _SMA2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _PROGRAMField;
        
        private string sYSTEMERRORField;
        
        private string eRRORLINEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
                this.RaisePropertyChanged("_PROGRAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SYSTEM-ERROR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SYSTEMERROR {
            get {
                return this.sYSTEMERRORField;
            }
            set {
                this.sYSTEMERRORField = value;
                this.RaisePropertyChanged("SYSTEMERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERROR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ERRORLINE {
            get {
                return this.eRRORLINEField;
            }
            set {
                this.eRRORLINEField = value;
                this.RaisePropertyChanged("ERRORLINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
    public partial class RTTIE227Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _SMA2 _SMAField;
        
        private _EWAG2 _EWAGField;
        
        private _EAMT2 _EAMTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public _SMA2 _SMA {
            get {
                return this._SMAField;
            }
            set {
                this._SMAField = value;
                this.RaisePropertyChanged("_SMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_E-WAG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public _EWAG2 _EWAG {
            get {
                return this._EWAGField;
            }
            set {
                this._EWAGField = value;
                this.RaisePropertyChanged("_EWAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_E-AMT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public _EAMT2 _EAMT {
            get {
                return this._EAMTField;
            }
            set {
                this._EAMTField = value;
                this.RaisePropertyChanged("_EAMT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_E-AMT", Namespace="http://ISDEV.city.phila.local/RTTIE227.service:RTTIE227WS")]
    public partial class _EAMT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gROSSCOMPENSATIONXField;
        
        private string nONTAXABLECOMPXField;
        
        private string nETCOMPENSATIONXField;
        
        private string rESIDENTPAYROLLAXField;
        
        private string rESIDENTTAXDUEAXField;
        
        private string rESIDENTPAYROLLBXField;
        
        private string rESIDENTTAXDUEBXField;
        
        private string nONRESPAYROLLAXField;
        
        private string nONRESTAXDUEAXField;
        
        private string nONRESPAYROLLBXField;
        
        private string nONRESTAXDUEBXField;
        
        private string tOTALGROSSTAXDUEXField;
        
        private string tAXPAIDXField;
        
        private string tAXDUEXField;
        
        private string tAXOVERPAIDXField;
        
        private string pOSTINGDATEXField;
        
        private string fILINGDATEXField;
        
        private string uSERIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GROSS-COMPENSATION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string GROSSCOMPENSATIONX {
            get {
                return this.gROSSCOMPENSATIONXField;
            }
            set {
                this.gROSSCOMPENSATIONXField = value;
                this.RaisePropertyChanged("GROSSCOMPENSATIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-TAXABLE-COMP-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string NONTAXABLECOMPX {
            get {
                return this.nONTAXABLECOMPXField;
            }
            set {
                this.nONTAXABLECOMPXField = value;
                this.RaisePropertyChanged("NONTAXABLECOMPX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-COMPENSATION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string NETCOMPENSATIONX {
            get {
                return this.nETCOMPENSATIONXField;
            }
            set {
                this.nETCOMPENSATIONXField = value;
                this.RaisePropertyChanged("NETCOMPENSATIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-PAYROLL-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string RESIDENTPAYROLLAX {
            get {
                return this.rESIDENTPAYROLLAXField;
            }
            set {
                this.rESIDENTPAYROLLAXField = value;
                this.RaisePropertyChanged("RESIDENTPAYROLLAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-TAX-DUE-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string RESIDENTTAXDUEAX {
            get {
                return this.rESIDENTTAXDUEAXField;
            }
            set {
                this.rESIDENTTAXDUEAXField = value;
                this.RaisePropertyChanged("RESIDENTTAXDUEAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-PAYROLL-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string RESIDENTPAYROLLBX {
            get {
                return this.rESIDENTPAYROLLBXField;
            }
            set {
                this.rESIDENTPAYROLLBXField = value;
                this.RaisePropertyChanged("RESIDENTPAYROLLBX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-TAX-DUE-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string RESIDENTTAXDUEBX {
            get {
                return this.rESIDENTTAXDUEBXField;
            }
            set {
                this.rESIDENTTAXDUEBXField = value;
                this.RaisePropertyChanged("RESIDENTTAXDUEBX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-PAYROLL-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string NONRESPAYROLLAX {
            get {
                return this.nONRESPAYROLLAXField;
            }
            set {
                this.nONRESPAYROLLAXField = value;
                this.RaisePropertyChanged("NONRESPAYROLLAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-TAX-DUE-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string NONRESTAXDUEAX {
            get {
                return this.nONRESTAXDUEAXField;
            }
            set {
                this.nONRESTAXDUEAXField = value;
                this.RaisePropertyChanged("NONRESTAXDUEAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-PAYROLL-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string NONRESPAYROLLBX {
            get {
                return this.nONRESPAYROLLBXField;
            }
            set {
                this.nONRESPAYROLLBXField = value;
                this.RaisePropertyChanged("NONRESPAYROLLBX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-TAX-DUE-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string NONRESTAXDUEBX {
            get {
                return this.nONRESTAXDUEBXField;
            }
            set {
                this.nONRESTAXDUEBXField = value;
                this.RaisePropertyChanged("NONRESTAXDUEBX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-GROSS-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string TOTALGROSSTAXDUEX {
            get {
                return this.tOTALGROSSTAXDUEXField;
            }
            set {
                this.tOTALGROSSTAXDUEXField = value;
                this.RaisePropertyChanged("TOTALGROSSTAXDUEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-PAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string TAXPAIDX {
            get {
                return this.tAXPAIDXField;
            }
            set {
                this.tAXPAIDXField = value;
                this.RaisePropertyChanged("TAXPAIDX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string TAXDUEX {
            get {
                return this.tAXDUEXField;
            }
            set {
                this.tAXDUEXField = value;
                this.RaisePropertyChanged("TAXDUEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-OVERPAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string TAXOVERPAIDX {
            get {
                return this.tAXOVERPAIDXField;
            }
            set {
                this.tAXOVERPAIDXField = value;
                this.RaisePropertyChanged("TAXOVERPAIDX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POSTING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string POSTINGDATEX {
            get {
                return this.pOSTINGDATEXField;
            }
            set {
                this.pOSTINGDATEXField = value;
                this.RaisePropertyChanged("POSTINGDATEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FILING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string FILINGDATEX {
            get {
                return this.fILINGDATEXField;
            }
            set {
                this.fILINGDATEXField = value;
                this.RaisePropertyChanged("FILINGDATEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
                this.RaisePropertyChanged("USERID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_E-WAG", Namespace="http://ISDEV.city.phila.local/RTTIE227.service:RTTIE227WS")]
    public partial class _EWAG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string vERSIONXField;
        
        private string dOCUMENTCONTROLXField;
        
        private string aDJREFNOField;
        
        private string fEDERALIDNUMBERField;
        
        private string rETURNSTATUSField;
        
        private string sEQUENCENUMField;
        
        private string lASTUPDATEDATEXField;
        
        private string nUMBEROFRESIDENTSXField;
        
        private string nUMBEROFNONRESIDENTSXField;
        
        private string pHILAEMPLOYEESXField;
        
        private string tOTALEMPLOYEESXField;
        
        private string rESRATEAField;
        
        private string rESRATEBField;
        
        private string nONRATEAField;
        
        private string nONRATEBField;
        
        private string fREQUENCYField;
        
        private string dUEDATEField;
        
        private string pREPARERNAMEField;
        
        private string pREPARERPHONEField;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILADDRESSField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
                this.RaisePropertyChanged("ACCOUNTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
                this.RaisePropertyChanged("PERIODX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VERSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string VERSIONX {
            get {
                return this.vERSIONXField;
            }
            set {
                this.vERSIONXField = value;
                this.RaisePropertyChanged("VERSIONX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DOCUMENT-CONTROL-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string DOCUMENTCONTROLX {
            get {
                return this.dOCUMENTCONTROLXField;
            }
            set {
                this.dOCUMENTCONTROLXField = value;
                this.RaisePropertyChanged("DOCUMENTCONTROLX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJ-REFNO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string ADJREFNO {
            get {
                return this.aDJREFNOField;
            }
            set {
                this.aDJREFNOField = value;
                this.RaisePropertyChanged("ADJREFNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FEDERAL-ID-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string FEDERALIDNUMBER {
            get {
                return this.fEDERALIDNUMBERField;
            }
            set {
                this.fEDERALIDNUMBERField = value;
                this.RaisePropertyChanged("FEDERALIDNUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RETURN-STATUS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string RETURNSTATUS {
            get {
                return this.rETURNSTATUSField;
            }
            set {
                this.rETURNSTATUSField = value;
                this.RaisePropertyChanged("RETURNSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SEQUENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string SEQUENCENUM {
            get {
                return this.sEQUENCENUMField;
            }
            set {
                this.sEQUENCENUMField = value;
                this.RaisePropertyChanged("SEQUENCENUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LAST-UPDATE-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string LASTUPDATEDATEX {
            get {
                return this.lASTUPDATEDATEXField;
            }
            set {
                this.lASTUPDATEDATEXField = value;
                this.RaisePropertyChanged("LASTUPDATEDATEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NUMBER-OF-RESIDENTS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string NUMBEROFRESIDENTSX {
            get {
                return this.nUMBEROFRESIDENTSXField;
            }
            set {
                this.nUMBEROFRESIDENTSXField = value;
                this.RaisePropertyChanged("NUMBEROFRESIDENTSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NUMBER-OF-NON-RESIDENTS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string NUMBEROFNONRESIDENTSX {
            get {
                return this.nUMBEROFNONRESIDENTSXField;
            }
            set {
                this.nUMBEROFNONRESIDENTSXField = value;
                this.RaisePropertyChanged("NUMBEROFNONRESIDENTSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PHILA-EMPLOYEES-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string PHILAEMPLOYEESX {
            get {
                return this.pHILAEMPLOYEESXField;
            }
            set {
                this.pHILAEMPLOYEESXField = value;
                this.RaisePropertyChanged("PHILAEMPLOYEESX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-EMPLOYEES-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string TOTALEMPLOYEESX {
            get {
                return this.tOTALEMPLOYEESXField;
            }
            set {
                this.tOTALEMPLOYEESXField = value;
                this.RaisePropertyChanged("TOTALEMPLOYEESX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-RATE-A", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string RESRATEA {
            get {
                return this.rESRATEAField;
            }
            set {
                this.rESRATEAField = value;
                this.RaisePropertyChanged("RESRATEA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-RATE-B", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string RESRATEB {
            get {
                return this.rESRATEBField;
            }
            set {
                this.rESRATEBField = value;
                this.RaisePropertyChanged("RESRATEB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RATE-A", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string NONRATEA {
            get {
                return this.nONRATEAField;
            }
            set {
                this.nONRATEAField = value;
                this.RaisePropertyChanged("NONRATEA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RATE-B", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string NONRATEB {
            get {
                return this.nONRATEBField;
            }
            set {
                this.nONRATEBField = value;
                this.RaisePropertyChanged("NONRATEB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
                this.RaisePropertyChanged("FREQUENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DUE-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public string DUEDATE {
            get {
                return this.dUEDATEField;
            }
            set {
                this.dUEDATEField = value;
                this.RaisePropertyChanged("DUEDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
                this.RaisePropertyChanged("PREPARERNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public string PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
                this.RaisePropertyChanged("PREPARERPHONE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
                this.RaisePropertyChanged("PREPARERPHONEEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=22)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
                this.RaisePropertyChanged("PREPARERIPADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=23)]
        public string PREPAREREMAILADDRESS {
            get {
                return this.pREPAREREMAILADDRESSField;
            }
            set {
                this.pREPAREREMAILADDRESSField = value;
                this.RaisePropertyChanged("PREPAREREMAILADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=24)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
                this.RaisePropertyChanged("PREPARERTYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RTTIE227", WrapperNamespace="http://ISDEV.city.phila.local/RTTIE227.service:RTTIE227WS", IsWrapped=true)]
    public partial class RTTIE227Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
        public CopRevenueGov2.RTTIE227_Srvref.RTTIE227 RTTIE227;
        
        public RTTIE227Request() {
        }
        
        public RTTIE227Request(CopRevenueGov2.RTTIE227_Srvref.RTTIE227 RTTIE227) {
            this.RTTIE227 = RTTIE227;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RTTIE227Response", WrapperNamespace="http://ISDEV.city.phila.local/RTTIE227.service:RTTIE227WS", IsWrapped=true)]
    public partial class RTTIE227Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
        public CopRevenueGov2.RTTIE227_Srvref.RTTIE227Response RTTIE227Response;
        
        public RTTIE227Response1() {
        }
        
        public RTTIE227Response1(CopRevenueGov2.RTTIE227_Srvref.RTTIE227Response RTTIE227Response) {
            this.RTTIE227Response = RTTIE227Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RTTIE227WS_PortTypeChannel : CopRevenueGov2.RTTIE227_Srvref.RTTIE227WS_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RTTIE227WS_PortTypeClient : System.ServiceModel.ClientBase<CopRevenueGov2.RTTIE227_Srvref.RTTIE227WS_PortType>, CopRevenueGov2.RTTIE227_Srvref.RTTIE227WS_PortType {
        
        public RTTIE227WS_PortTypeClient() {
        }
        
        public RTTIE227WS_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RTTIE227WS_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RTTIE227WS_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RTTIE227WS_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CopRevenueGov2.RTTIE227_Srvref.RTTIE227Response1 CopRevenueGov2.RTTIE227_Srvref.RTTIE227WS_PortType.RTTIE227(CopRevenueGov2.RTTIE227_Srvref.RTTIE227Request request) {
            return base.Channel.RTTIE227(request);
        }
        
        public CopRevenueGov2.RTTIE227_Srvref.RTTIE227Response RTTIE227(CopRevenueGov2.RTTIE227_Srvref.RTTIE227 RTTIE2271) {
            CopRevenueGov2.RTTIE227_Srvref.RTTIE227Request inValue = new CopRevenueGov2.RTTIE227_Srvref.RTTIE227Request();
            inValue.RTTIE227 = RTTIE2271;
            CopRevenueGov2.RTTIE227_Srvref.RTTIE227Response1 retVal = ((CopRevenueGov2.RTTIE227_Srvref.RTTIE227WS_PortType)(this)).RTTIE227(inValue);
            return retVal.RTTIE227Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CopRevenueGov2.RTTIE227_Srvref.RTTIE227Response1> CopRevenueGov2.RTTIE227_Srvref.RTTIE227WS_PortType.RTTIE227Async(CopRevenueGov2.RTTIE227_Srvref.RTTIE227Request request) {
            return base.Channel.RTTIE227Async(request);
        }
        
        public System.Threading.Tasks.Task<CopRevenueGov2.RTTIE227_Srvref.RTTIE227Response1> RTTIE227Async(CopRevenueGov2.RTTIE227_Srvref.RTTIE227 RTTIE227) {
            CopRevenueGov2.RTTIE227_Srvref.RTTIE227Request inValue = new CopRevenueGov2.RTTIE227_Srvref.RTTIE227Request();
            inValue.RTTIE227 = RTTIE227;
            return ((CopRevenueGov2.RTTIE227_Srvref.RTTIE227WS_PortType)(this)).RTTIE227Async(inValue);
        }
    }
}
