//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace CopRevenueGov2.SIT_RTTIE036_SrvRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TIPSACCDSOAP11Binding", Namespace="http://namespace.softwareag.com/entirex/xml/mapping")]
    public partial class RTTIE036 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallRTTIE036OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RTTIE036() {
            this.Url = "http://istest.city.phila.local:10010/wsstack/services/RTTIE036.TIPSACCDSOAP11Port" +
                "/";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallRTTIE036CompletedEventHandler CallRTTIE036Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RTTIE036", RequestElementName="RTTIE036", RequestNamespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE036", ResponseElementName="RTTIE036Response", ResponseNamespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE036", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_SMA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RTTIE036Response_SMA CallRTTIE036([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] RTTIE036_SMA _SMA, [System.Xml.Serialization.XmlElementAttribute("_E-SIT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] RTTIE036_ESIT _ESIT, [System.Xml.Serialization.XmlElementAttribute("_E-AMT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] RTTIE036_EAMT _EAMT, [System.Xml.Serialization.XmlElementAttribute("_E-SIT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out RTTIE036Response_ESIT _ESIT1, [System.Xml.Serialization.XmlElementAttribute("_E-AMT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out RTTIE036Response_EAMT _EAMT1) {
            object[] results = this.Invoke("CallRTTIE036", new object[] {
                        _SMA,
                        _ESIT,
                        _EAMT});
            _ESIT1 = ((RTTIE036Response_ESIT)(results[1]));
            _EAMT1 = ((RTTIE036Response_EAMT)(results[2]));
            return ((RTTIE036Response_SMA)(results[0]));
        }
        
        /// <remarks/>
        public void CallRTTIE036Async(RTTIE036_SMA _SMA, RTTIE036_ESIT _ESIT, RTTIE036_EAMT _EAMT) {
            this.CallRTTIE036Async(_SMA, _ESIT, _EAMT, null);
        }
        
        /// <remarks/>
        public void CallRTTIE036Async(RTTIE036_SMA _SMA, RTTIE036_ESIT _ESIT, RTTIE036_EAMT _EAMT, object userState) {
            if ((this.CallRTTIE036OperationCompleted == null)) {
                this.CallRTTIE036OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallRTTIE036OperationCompleted);
            }
            this.InvokeAsync("CallRTTIE036", new object[] {
                        _SMA,
                        _ESIT,
                        _EAMT}, this.CallRTTIE036OperationCompleted, userState);
        }
        
        private void OnCallRTTIE036OperationCompleted(object arg) {
            if ((this.CallRTTIE036Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallRTTIE036Completed(this, new CallRTTIE036CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE036")]
    public partial class RTTIE036_SMA {
        
        private string _PROGRAMField;
        
        private decimal sYSTEMERRORField;
        
        private bool sYSTEMERRORFieldSpecified;
        
        private decimal eRRORLINEField;
        
        private bool eRRORLINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SYSTEM-ERROR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SYSTEMERROR {
            get {
                return this.sYSTEMERRORField;
            }
            set {
                this.sYSTEMERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SYSTEMERRORSpecified {
            get {
                return this.sYSTEMERRORFieldSpecified;
            }
            set {
                this.sYSTEMERRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERROR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERRORLINE {
            get {
                return this.eRRORLINEField;
            }
            set {
                this.eRRORLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORLINESpecified {
            get {
                return this.eRRORLINEFieldSpecified;
            }
            set {
                this.eRRORLINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE036")]
    public partial class RTTIE036_ESIT {
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string vERSIONXField;
        
        private string rETURNSTATUSField;
        
        private string lASTUPDATEDATEXField;
        
        private string rECORDINGDATEXField;
        
        private string eXTENSIONDATEXField;
        
        private string sEQUENCENUMField;
        
        private string aDJUSTMENTREFERENCENUMField;
        
        private string rATEField;
        
        private string pREPARERNAMEField;
        
        private decimal pREPARERPHONEField;
        
        private bool pREPARERPHONEFieldSpecified;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILADDRESSField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VERSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VERSIONX {
            get {
                return this.vERSIONXField;
            }
            set {
                this.vERSIONXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RETURN-STATUS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETURNSTATUS {
            get {
                return this.rETURNSTATUSField;
            }
            set {
                this.rETURNSTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LAST-UPDATE-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LASTUPDATEDATEX {
            get {
                return this.lASTUPDATEDATEXField;
            }
            set {
                this.lASTUPDATEDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RECORDING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECORDINGDATEX {
            get {
                return this.rECORDINGDATEXField;
            }
            set {
                this.rECORDINGDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EXTENSION-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXTENSIONDATEX {
            get {
                return this.eXTENSIONDATEXField;
            }
            set {
                this.eXTENSIONDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SEQUENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEQUENCENUM {
            get {
                return this.sEQUENCENUMField;
            }
            set {
                this.sEQUENCENUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJUSTMENT-REFERENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADJUSTMENTREFERENCENUM {
            get {
                return this.aDJUSTMENTREFERENCENUMField;
            }
            set {
                this.aDJUSTMENTREFERENCENUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RATE {
            get {
                return this.rATEField;
            }
            set {
                this.rATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PREPARERPHONESpecified {
            get {
                return this.pREPARERPHONEFieldSpecified;
            }
            set {
                this.pREPARERPHONEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPAREREMAILADDRESS {
            get {
                return this.pREPAREREMAILADDRESSField;
            }
            set {
                this.pREPAREREMAILADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE036")]
    public partial class RTTIE036_EAMT {
        
        private string nETTAXABLEDIVIDENDSXField;
        
        private string tAXABLEINTERESTXField;
        
        private string sCORPDISTRIBUTIONSXField;
        
        private string pARTNERSHIPINCOMEXField;
        
        private string bENEFICIARYINCOMEXField;
        
        private string sHORTTERMGAINSXField;
        
        private string nETRENTALINCOMEXField;
        
        private string oTHERTAXABLEINCOMEXField;
        
        private string tOTALTAXABLEINCOMEXField;
        
        private string dEDUCTIBLEEXPENSESXField;
        
        private string nETTAXABLEINCOMEXField;
        
        private string gROSSTAXDUEXField;
        
        private string cREDITSXField;
        
        private string tAXDUEXField;
        
        private string rEFUNDAMTXField;
        
        private string oVERPAYMENTXField;
        
        private string uSERIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-TAXABLE-DIVIDENDS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETTAXABLEDIVIDENDSX {
            get {
                return this.nETTAXABLEDIVIDENDSXField;
            }
            set {
                this.nETTAXABLEDIVIDENDSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAXABLE-INTEREST-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXABLEINTERESTX {
            get {
                return this.tAXABLEINTERESTXField;
            }
            set {
                this.tAXABLEINTERESTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("S-CORP-DISTRIBUTIONS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SCORPDISTRIBUTIONSX {
            get {
                return this.sCORPDISTRIBUTIONSXField;
            }
            set {
                this.sCORPDISTRIBUTIONSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PARTNERSHIP-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PARTNERSHIPINCOMEX {
            get {
                return this.pARTNERSHIPINCOMEXField;
            }
            set {
                this.pARTNERSHIPINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BENEFICIARY-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BENEFICIARYINCOMEX {
            get {
                return this.bENEFICIARYINCOMEXField;
            }
            set {
                this.bENEFICIARYINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHORT-TERM-GAINS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SHORTTERMGAINSX {
            get {
                return this.sHORTTERMGAINSXField;
            }
            set {
                this.sHORTTERMGAINSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-RENTAL-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETRENTALINCOMEX {
            get {
                return this.nETRENTALINCOMEXField;
            }
            set {
                this.nETRENTALINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OTHER-TAXABLE-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OTHERTAXABLEINCOMEX {
            get {
                return this.oTHERTAXABLEINCOMEXField;
            }
            set {
                this.oTHERTAXABLEINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-TAXABLE-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALTAXABLEINCOMEX {
            get {
                return this.tOTALTAXABLEINCOMEXField;
            }
            set {
                this.tOTALTAXABLEINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DEDUCTIBLE-EXPENSES-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEDUCTIBLEEXPENSESX {
            get {
                return this.dEDUCTIBLEEXPENSESXField;
            }
            set {
                this.dEDUCTIBLEEXPENSESXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-TAXABLE-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETTAXABLEINCOMEX {
            get {
                return this.nETTAXABLEINCOMEXField;
            }
            set {
                this.nETTAXABLEINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GROSS-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GROSSTAXDUEX {
            get {
                return this.gROSSTAXDUEXField;
            }
            set {
                this.gROSSTAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CREDITS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREDITSX {
            get {
                return this.cREDITSXField;
            }
            set {
                this.cREDITSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXDUEX {
            get {
                return this.tAXDUEXField;
            }
            set {
                this.tAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("REFUND-AMT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REFUNDAMTX {
            get {
                return this.rEFUNDAMTXField;
            }
            set {
                this.rEFUNDAMTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OVERPAYMENT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OVERPAYMENTX {
            get {
                return this.oVERPAYMENTXField;
            }
            set {
                this.oVERPAYMENTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE036")]
    public partial class RTTIE036Response_SMA {
        
        private string _PROGRAMField;
        
        private decimal sYSTEMERRORField;
        
        private bool sYSTEMERRORFieldSpecified;
        
        private decimal eRRORLINEField;
        
        private bool eRRORLINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SYSTEM-ERROR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SYSTEMERROR {
            get {
                return this.sYSTEMERRORField;
            }
            set {
                this.sYSTEMERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SYSTEMERRORSpecified {
            get {
                return this.sYSTEMERRORFieldSpecified;
            }
            set {
                this.sYSTEMERRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERROR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERRORLINE {
            get {
                return this.eRRORLINEField;
            }
            set {
                this.eRRORLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORLINESpecified {
            get {
                return this.eRRORLINEFieldSpecified;
            }
            set {
                this.eRRORLINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE036")]
    public partial class RTTIE036Response_ESIT {
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string vERSIONXField;
        
        private string rETURNSTATUSField;
        
        private string lASTUPDATEDATEXField;
        
        private string rECORDINGDATEXField;
        
        private string eXTENSIONDATEXField;
        
        private string sEQUENCENUMField;
        
        private string aDJUSTMENTREFERENCENUMField;
        
        private string rATEField;
        
        private string pREPARERNAMEField;
        
        private decimal pREPARERPHONEField;
        
        private bool pREPARERPHONEFieldSpecified;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILADDRESSField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VERSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VERSIONX {
            get {
                return this.vERSIONXField;
            }
            set {
                this.vERSIONXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RETURN-STATUS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETURNSTATUS {
            get {
                return this.rETURNSTATUSField;
            }
            set {
                this.rETURNSTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LAST-UPDATE-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LASTUPDATEDATEX {
            get {
                return this.lASTUPDATEDATEXField;
            }
            set {
                this.lASTUPDATEDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RECORDING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECORDINGDATEX {
            get {
                return this.rECORDINGDATEXField;
            }
            set {
                this.rECORDINGDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EXTENSION-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXTENSIONDATEX {
            get {
                return this.eXTENSIONDATEXField;
            }
            set {
                this.eXTENSIONDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SEQUENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEQUENCENUM {
            get {
                return this.sEQUENCENUMField;
            }
            set {
                this.sEQUENCENUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJUSTMENT-REFERENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADJUSTMENTREFERENCENUM {
            get {
                return this.aDJUSTMENTREFERENCENUMField;
            }
            set {
                this.aDJUSTMENTREFERENCENUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RATE {
            get {
                return this.rATEField;
            }
            set {
                this.rATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PREPARERPHONESpecified {
            get {
                return this.pREPARERPHONEFieldSpecified;
            }
            set {
                this.pREPARERPHONEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPAREREMAILADDRESS {
            get {
                return this.pREPAREREMAILADDRESSField;
            }
            set {
                this.pREPAREREMAILADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE036")]
    public partial class RTTIE036Response_EAMT {
        
        private string nETTAXABLEDIVIDENDSXField;
        
        private string tAXABLEINTERESTXField;
        
        private string sCORPDISTRIBUTIONSXField;
        
        private string pARTNERSHIPINCOMEXField;
        
        private string bENEFICIARYINCOMEXField;
        
        private string sHORTTERMGAINSXField;
        
        private string nETRENTALINCOMEXField;
        
        private string oTHERTAXABLEINCOMEXField;
        
        private string tOTALTAXABLEINCOMEXField;
        
        private string dEDUCTIBLEEXPENSESXField;
        
        private string nETTAXABLEINCOMEXField;
        
        private string gROSSTAXDUEXField;
        
        private string cREDITSXField;
        
        private string tAXDUEXField;
        
        private string rEFUNDAMTXField;
        
        private string oVERPAYMENTXField;
        
        private string uSERIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-TAXABLE-DIVIDENDS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETTAXABLEDIVIDENDSX {
            get {
                return this.nETTAXABLEDIVIDENDSXField;
            }
            set {
                this.nETTAXABLEDIVIDENDSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAXABLE-INTEREST-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXABLEINTERESTX {
            get {
                return this.tAXABLEINTERESTXField;
            }
            set {
                this.tAXABLEINTERESTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("S-CORP-DISTRIBUTIONS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SCORPDISTRIBUTIONSX {
            get {
                return this.sCORPDISTRIBUTIONSXField;
            }
            set {
                this.sCORPDISTRIBUTIONSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PARTNERSHIP-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PARTNERSHIPINCOMEX {
            get {
                return this.pARTNERSHIPINCOMEXField;
            }
            set {
                this.pARTNERSHIPINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BENEFICIARY-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BENEFICIARYINCOMEX {
            get {
                return this.bENEFICIARYINCOMEXField;
            }
            set {
                this.bENEFICIARYINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHORT-TERM-GAINS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SHORTTERMGAINSX {
            get {
                return this.sHORTTERMGAINSXField;
            }
            set {
                this.sHORTTERMGAINSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-RENTAL-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETRENTALINCOMEX {
            get {
                return this.nETRENTALINCOMEXField;
            }
            set {
                this.nETRENTALINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OTHER-TAXABLE-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OTHERTAXABLEINCOMEX {
            get {
                return this.oTHERTAXABLEINCOMEXField;
            }
            set {
                this.oTHERTAXABLEINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-TAXABLE-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALTAXABLEINCOMEX {
            get {
                return this.tOTALTAXABLEINCOMEXField;
            }
            set {
                this.tOTALTAXABLEINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DEDUCTIBLE-EXPENSES-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEDUCTIBLEEXPENSESX {
            get {
                return this.dEDUCTIBLEEXPENSESXField;
            }
            set {
                this.dEDUCTIBLEEXPENSESXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-TAXABLE-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETTAXABLEINCOMEX {
            get {
                return this.nETTAXABLEINCOMEXField;
            }
            set {
                this.nETTAXABLEINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GROSS-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GROSSTAXDUEX {
            get {
                return this.gROSSTAXDUEXField;
            }
            set {
                this.gROSSTAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CREDITS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREDITSX {
            get {
                return this.cREDITSXField;
            }
            set {
                this.cREDITSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXDUEX {
            get {
                return this.tAXDUEXField;
            }
            set {
                this.tAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("REFUND-AMT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REFUNDAMTX {
            get {
                return this.rEFUNDAMTXField;
            }
            set {
                this.rEFUNDAMTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OVERPAYMENT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OVERPAYMENTX {
            get {
                return this.oVERPAYMENTXField;
            }
            set {
                this.oVERPAYMENTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallRTTIE036CompletedEventHandler(object sender, CallRTTIE036CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallRTTIE036CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallRTTIE036CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RTTIE036Response_SMA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RTTIE036Response_SMA)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public RTTIE036Response_ESIT _ESIT1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RTTIE036Response_ESIT)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public RTTIE036Response_EAMT _EAMT1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RTTIE036Response_EAMT)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591