//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace CopRevenueGov2.RTTIE010_SrvRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TIPSACCDSOAP11Binding", Namespace="http://namespace.softwareag.com/entirex/xml/mapping")]
    public partial class RTTIE010 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallRTTIE010OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RTTIE010() {
            //this.Url = global::CopRevenueGov2.Properties.Settings.Default.CopRevenueGov2_RTTIE010_SrvRef_RTTIE010;
            this.Url = "http://ISTEST.City.Phila.Local:10010/wsstack/services/RTTIE010.TIPSACCDSOAP11Port/";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallRTTIE010CompletedEventHandler CallRTTIE010Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RTTIE010", RequestElementName="RTTIE010", RequestNamespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010", ResponseElementName="RTTIE010Response", ResponseNamespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_SMA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RTTIE010Response_SMA CallRTTIE010([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] RTTIE010_EMI _EMI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] RTTIE010_ETA _ETA, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] RTTIE010_ECHK _ECHK, [System.Xml.Serialization.XmlElementAttribute("_ENA-1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] RTTIE010_ENA1 _ENA1, [System.Xml.Serialization.XmlElementAttribute("_ENA-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] RTTIE010_ENA2 _ENA2, [System.Xml.Serialization.XmlElementAttribute("_EMI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out RTTIE010Response_EMI _EMI1, [System.Xml.Serialization.XmlElementAttribute("_ETA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out RTTIE010Response_ETA _ETA1, [System.Xml.Serialization.XmlElementAttribute("_ECHK", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out RTTIE010Response_ECHK _ECHK1, [System.Xml.Serialization.XmlElementAttribute("_ENA-1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out RTTIE010Response_ENA1 _ENA11, [System.Xml.Serialization.XmlElementAttribute("_ENA-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out RTTIE010Response_ENA2 _ENA21) {
            object[] results = this.Invoke("CallRTTIE010", new object[] {
                        _EMI,
                        _ETA,
                        _ECHK,
                        _ENA1,
                        _ENA2});
            _EMI1 = ((RTTIE010Response_EMI)(results[1]));
            _ETA1 = ((RTTIE010Response_ETA)(results[2]));
            _ECHK1 = ((RTTIE010Response_ECHK)(results[3]));
            _ENA11 = ((RTTIE010Response_ENA1)(results[4]));
            _ENA21 = ((RTTIE010Response_ENA2)(results[5]));
            return ((RTTIE010Response_SMA)(results[0]));
        }
        
        /// <remarks/>
        public void CallRTTIE010Async(RTTIE010_EMI _EMI, RTTIE010_ETA _ETA, RTTIE010_ECHK _ECHK, RTTIE010_ENA1 _ENA1, RTTIE010_ENA2 _ENA2) {
            this.CallRTTIE010Async(_EMI, _ETA, _ECHK, _ENA1, _ENA2, null);
        }
        
        /// <remarks/>
        public void CallRTTIE010Async(RTTIE010_EMI _EMI, RTTIE010_ETA _ETA, RTTIE010_ECHK _ECHK, RTTIE010_ENA1 _ENA1, RTTIE010_ENA2 _ENA2, object userState) {
            if ((this.CallRTTIE010OperationCompleted == null)) {
                this.CallRTTIE010OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallRTTIE010OperationCompleted);
            }
            this.InvokeAsync("CallRTTIE010", new object[] {
                        _EMI,
                        _ETA,
                        _ECHK,
                        _ENA1,
                        _ENA2}, this.CallRTTIE010OperationCompleted, userState);
        }
        
        private void OnCallRTTIE010OperationCompleted(object arg) {
            if ((this.CallRTTIE010Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallRTTIE010Completed(this, new CallRTTIE010CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010_EMI {
        
        private RTTIE010_EMI_ENTITYMASTERINFO _ENTITYMASTERINFOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_ENTITY-MASTER-INFO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RTTIE010_EMI_ENTITYMASTERINFO _ENTITYMASTERINFO {
            get {
                return this._ENTITYMASTERINFOField;
            }
            set {
                this._ENTITYMASTERINFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010_EMI_ENTITYMASTERINFO {
        
        private string fUNCTIONCODEField;
        
        private decimal eNTITYTYPEField;
        
        private bool eNTITYTYPEFieldSpecified;
        
        private string eNTITYIDField;
        
        private string aCCOUNTIDField;
        
        private decimal nAICFEDERALCODEField;
        
        private bool nAICFEDERALCODEFieldSpecified;
        
        private decimal sICFEDERALCODEField;
        
        private bool sICFEDERALCODEFieldSpecified;
        
        private decimal bUSINESSSTARTDATEField;
        
        private bool bUSINESSSTARTDATEFieldSpecified;
        
        private decimal oRGANIZATIONTYPEField;
        
        private bool oRGANIZATIONTYPEFieldSpecified;
        
        private decimal bUSINESSORIGINField;
        
        private bool bUSINESSORIGINFieldSpecified;
        
        private string bUSINESSGENDERField;
        
        private string bUSINESSOTHERField;
        
        private decimal pINNUMBERField;
        
        private bool pINNUMBERFieldSpecified;
        
        private string pINSWITCHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ENTITYTYPE {
            get {
                return this.eNTITYTYPEField;
            }
            set {
                this.eNTITYTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENTITYTYPESpecified {
            get {
                return this.eNTITYTYPEFieldSpecified;
            }
            set {
                this.eNTITYTYPEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NAIC-FEDERAL-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NAICFEDERALCODE {
            get {
                return this.nAICFEDERALCODEField;
            }
            set {
                this.nAICFEDERALCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAICFEDERALCODESpecified {
            get {
                return this.nAICFEDERALCODEFieldSpecified;
            }
            set {
                this.nAICFEDERALCODEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SIC-FEDERAL-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SICFEDERALCODE {
            get {
                return this.sICFEDERALCODEField;
            }
            set {
                this.sICFEDERALCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SICFEDERALCODESpecified {
            get {
                return this.sICFEDERALCODEFieldSpecified;
            }
            set {
                this.sICFEDERALCODEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-START-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BUSINESSSTARTDATE {
            get {
                return this.bUSINESSSTARTDATEField;
            }
            set {
                this.bUSINESSSTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BUSINESSSTARTDATESpecified {
            get {
                return this.bUSINESSSTARTDATEFieldSpecified;
            }
            set {
                this.bUSINESSSTARTDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ORGANIZATION-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ORGANIZATIONTYPE {
            get {
                return this.oRGANIZATIONTYPEField;
            }
            set {
                this.oRGANIZATIONTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORGANIZATIONTYPESpecified {
            get {
                return this.oRGANIZATIONTYPEFieldSpecified;
            }
            set {
                this.oRGANIZATIONTYPEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-ORIGIN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BUSINESSORIGIN {
            get {
                return this.bUSINESSORIGINField;
            }
            set {
                this.bUSINESSORIGINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BUSINESSORIGINSpecified {
            get {
                return this.bUSINESSORIGINFieldSpecified;
            }
            set {
                this.bUSINESSORIGINFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-GENDER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSINESSGENDER {
            get {
                return this.bUSINESSGENDERField;
            }
            set {
                this.bUSINESSGENDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-OTHER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSINESSOTHER {
            get {
                return this.bUSINESSOTHERField;
            }
            set {
                this.bUSINESSOTHERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PIN-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PINNUMBER {
            get {
                return this.pINNUMBERField;
            }
            set {
                this.pINNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PINNUMBERSpecified {
            get {
                return this.pINNUMBERFieldSpecified;
            }
            set {
                this.pINNUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PIN-SWITCH", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PINSWITCH {
            get {
                return this.pINSWITCHField;
            }
            set {
                this.pINSWITCHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010_ETA {
        
        private RTTIE010_ETA_ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_ENTITY-TAX-ACCOUNTSs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_ENTITY-TAX-ACCOUNTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RTTIE010_ETA_ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSs {
            get {
                return this._ENTITYTAXACCOUNTSsField;
            }
            set {
                this._ENTITYTAXACCOUNTSsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010_ETA_ENTITYTAXACCOUNTS {
        
        private string fUNCTIONCODEField;
        
        private decimal aCCOUNTField;
        
        private bool aCCOUNTFieldSpecified;
        
        private decimal sTARTDATEField;
        
        private bool sTARTDATEFieldSpecified;
        
        private string wAGMONTHLYGROSSField;
        
        private RTTIE010_ETA_ENTITYTAXACCOUNTSBPTNEWAPPLICATION bPTNEWAPPLICATIONField;
        
        private string pRKIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ACCOUNT {
            get {
                return this.aCCOUNTField;
            }
            set {
                this.aCCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ACCOUNTSpecified {
            get {
                return this.aCCOUNTFieldSpecified;
            }
            set {
                this.aCCOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("START-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal STARTDATE {
            get {
                return this.sTARTDATEField;
            }
            set {
                this.sTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STARTDATESpecified {
            get {
                return this.sTARTDATEFieldSpecified;
            }
            set {
                this.sTARTDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WAG-MONTHLY-GROSS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WAGMONTHLYGROSS {
            get {
                return this.wAGMONTHLYGROSSField;
            }
            set {
                this.wAGMONTHLYGROSSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPT-NEW-APPLICATION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RTTIE010_ETA_ENTITYTAXACCOUNTSBPTNEWAPPLICATION BPTNEWAPPLICATION {
            get {
                return this.bPTNEWAPPLICATIONField;
            }
            set {
                this.bPTNEWAPPLICATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRK-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRKID {
            get {
                return this.pRKIDField;
            }
            set {
                this.pRKIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010_ETA_ENTITYTAXACCOUNTSBPTNEWAPPLICATION {
        
        private string bPTNAAPPLYFOREXEMPTIONField;
        
        private string bPTNAREACTIVATINGField;
        
        private string bPTNAAFFILIATEDField;
        
        private string bPTNANEWOWNERField;
        
        private string bPTNAREALESTATEField;
        
        private string bPTNAACCEPTEDField;
        
        private string bPTNACOMPLYYEAR1Field;
        
        private string bPTNACOMPLYYEAR2Field;
        
        private string bPTNASTATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-APPLY-FOR-EXEMPTION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNAAPPLYFOREXEMPTION {
            get {
                return this.bPTNAAPPLYFOREXEMPTIONField;
            }
            set {
                this.bPTNAAPPLYFOREXEMPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-REACTIVATING", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNAREACTIVATING {
            get {
                return this.bPTNAREACTIVATINGField;
            }
            set {
                this.bPTNAREACTIVATINGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-AFFILIATED", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNAAFFILIATED {
            get {
                return this.bPTNAAFFILIATEDField;
            }
            set {
                this.bPTNAAFFILIATEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-NEWOWNER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNANEWOWNER {
            get {
                return this.bPTNANEWOWNERField;
            }
            set {
                this.bPTNANEWOWNERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-REALESTATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNAREALESTATE {
            get {
                return this.bPTNAREALESTATEField;
            }
            set {
                this.bPTNAREALESTATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-ACCEPTED", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNAACCEPTED {
            get {
                return this.bPTNAACCEPTEDField;
            }
            set {
                this.bPTNAACCEPTEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-COMPLY-YEAR1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNACOMPLYYEAR1 {
            get {
                return this.bPTNACOMPLYYEAR1Field;
            }
            set {
                this.bPTNACOMPLYYEAR1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-COMPLY-YEAR2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNACOMPLYYEAR2 {
            get {
                return this.bPTNACOMPLYYEAR2Field;
            }
            set {
                this.bPTNACOMPLYYEAR2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-STATUS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNASTATUS {
            get {
                return this.bPTNASTATUSField;
            }
            set {
                this.bPTNASTATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010_ECHK {
        
        private RTTIE010_ECHK_ECHECK _ECHECKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_E-CHECK", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RTTIE010_ECHK_ECHECK _ECHECK {
            get {
                return this._ECHECKField;
            }
            set {
                this._ECHECKField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010_ECHK_ECHECK {
        
        private string fUNCTIONCODEField;
        
        private string tRANSITROUTINGNUMBERField;
        
        private string bANKACCOUNTNUMBERField;
        
        private string bANKACCOUNTTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TRANSIT-ROUTING-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANSITROUTINGNUMBER {
            get {
                return this.tRANSITROUTINGNUMBERField;
            }
            set {
                this.tRANSITROUTINGNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BANK-ACCOUNT-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANKACCOUNTNUMBER {
            get {
                return this.bANKACCOUNTNUMBERField;
            }
            set {
                this.bANKACCOUNTNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BANK-ACCOUNT-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANKACCOUNTTYPE {
            get {
                return this.bANKACCOUNTTYPEField;
            }
            set {
                this.bANKACCOUNTTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010_ENA1 {
        
        private RTTIE010_ENA1_NAMADDR1[] _NAMADDR1sField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_NAM-ADDR-1s", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_NAM-ADDR-1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RTTIE010_ENA1_NAMADDR1[] _NAMADDR1s {
            get {
                return this._NAMADDR1sField;
            }
            set {
                this._NAMADDR1sField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010_ENA1_NAMADDR1 {
        
        private string fUNCTIONCODEField;
        
        private decimal eNTITYTYPEField;
        
        private bool eNTITYTYPEFieldSpecified;
        
        private string eNTITYIDField;
        
        private string eNTITYNAMEField;
        
        private string tRADENAMEField;
        
        private decimal aDDRESSTYPEField;
        
        private bool aDDRESSTYPEFieldSpecified;
        
        private decimal rELATIONSHIPCODEField;
        
        private bool rELATIONSHIPCODEFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ENTITYTYPE {
            get {
                return this.eNTITYTYPEField;
            }
            set {
                this.eNTITYTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENTITYTYPESpecified {
            get {
                return this.eNTITYTYPEFieldSpecified;
            }
            set {
                this.eNTITYTYPEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYNAME {
            get {
                return this.eNTITYNAMEField;
            }
            set {
                this.eNTITYNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TRADE-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRADENAME {
            get {
                return this.tRADENAMEField;
            }
            set {
                this.tRADENAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ADDRESSTYPE {
            get {
                return this.aDDRESSTYPEField;
            }
            set {
                this.aDDRESSTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ADDRESSTYPESpecified {
            get {
                return this.aDDRESSTYPEFieldSpecified;
            }
            set {
                this.aDDRESSTYPEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RELATIONSHIP-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal RELATIONSHIPCODE {
            get {
                return this.rELATIONSHIPCODEField;
            }
            set {
                this.rELATIONSHIPCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RELATIONSHIPCODESpecified {
            get {
                return this.rELATIONSHIPCODEFieldSpecified;
            }
            set {
                this.rELATIONSHIPCODEFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010_ENA2 {
        
        private RTTIE010_ENA2_NAMADDR2[] _NAMADDR2sField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_NAM-ADDR-2s", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_NAM-ADDR-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RTTIE010_ENA2_NAMADDR2[] _NAMADDR2s {
            get {
                return this._NAMADDR2sField;
            }
            set {
                this._NAMADDR2sField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010_ENA2_NAMADDR2 {
        
        private string aTTENTIONField;
        
        private string aDDRESSLINE1Field;
        
        private string aDDRESSLINE2Field;
        
        private string cITYField;
        
        private string sTATEField;
        
        private string zIPCODEField;
        
        private decimal bUSINESSPHONENUMBERField;
        
        private bool bUSINESSPHONENUMBERFieldSpecified;
        
        private string bUSINESSPHONEEXTENSIONField;
        
        private decimal bUSINESSFAXField;
        
        private bool bUSINESSFAXFieldSpecified;
        
        private decimal oTHERPHONENUMBERField;
        
        private bool oTHERPHONENUMBERFieldSpecified;
        
        private string eMAILADDRField;
        
        private decimal tINAMSEQUENCENUMBERField;
        
        private bool tINAMSEQUENCENUMBERFieldSpecified;
        
        private decimal tIADRSEQUENCENUMBERField;
        
        private bool tIADRSEQUENCENUMBERFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATTENTION {
            get {
                return this.aTTENTIONField;
            }
            set {
                this.aTTENTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE-1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRESSLINE1 {
            get {
                return this.aDDRESSLINE1Field;
            }
            set {
                this.aDDRESSLINE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRESSLINE2 {
            get {
                return this.aDDRESSLINE2Field;
            }
            set {
                this.aDDRESSLINE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZIP-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIPCODE {
            get {
                return this.zIPCODEField;
            }
            set {
                this.zIPCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-PHONE-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BUSINESSPHONENUMBER {
            get {
                return this.bUSINESSPHONENUMBERField;
            }
            set {
                this.bUSINESSPHONENUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BUSINESSPHONENUMBERSpecified {
            get {
                return this.bUSINESSPHONENUMBERFieldSpecified;
            }
            set {
                this.bUSINESSPHONENUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-PHONE-EXTENSION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSINESSPHONEEXTENSION {
            get {
                return this.bUSINESSPHONEEXTENSIONField;
            }
            set {
                this.bUSINESSPHONEEXTENSIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-FAX", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BUSINESSFAX {
            get {
                return this.bUSINESSFAXField;
            }
            set {
                this.bUSINESSFAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BUSINESSFAXSpecified {
            get {
                return this.bUSINESSFAXFieldSpecified;
            }
            set {
                this.bUSINESSFAXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OTHER-PHONE-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal OTHERPHONENUMBER {
            get {
                return this.oTHERPHONENUMBERField;
            }
            set {
                this.oTHERPHONENUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OTHERPHONENUMBERSpecified {
            get {
                return this.oTHERPHONENUMBERFieldSpecified;
            }
            set {
                this.oTHERPHONENUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("E-MAIL-ADDR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMAILADDR {
            get {
                return this.eMAILADDRField;
            }
            set {
                this.eMAILADDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TINAM-SEQUENCE-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TINAMSEQUENCENUMBER {
            get {
                return this.tINAMSEQUENCENUMBERField;
            }
            set {
                this.tINAMSEQUENCENUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TINAMSEQUENCENUMBERSpecified {
            get {
                return this.tINAMSEQUENCENUMBERFieldSpecified;
            }
            set {
                this.tINAMSEQUENCENUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TIADR-SEQUENCE-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TIADRSEQUENCENUMBER {
            get {
                return this.tIADRSEQUENCENUMBERField;
            }
            set {
                this.tIADRSEQUENCENUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TIADRSEQUENCENUMBERSpecified {
            get {
                return this.tIADRSEQUENCENUMBERFieldSpecified;
            }
            set {
                this.tIADRSEQUENCENUMBERFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010Response_SMA {
        
        private RTTIE010Response_SMA_SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SYSTEM-MESSAGE-AREA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RTTIE010Response_SMA_SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREA {
            get {
                return this._SYSTEMMESSAGEAREAField;
            }
            set {
                this._SYSTEMMESSAGEAREAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010Response_SMA_SYSTEMMESSAGEAREA {
        
        private string _PROGRAMField;
        
        private decimal eRRORField;
        
        private bool eRRORFieldSpecified;
        
        private decimal lINEField;
        
        private bool lINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORSpecified {
            get {
                return this.eRRORFieldSpecified;
            }
            set {
                this.eRRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal LINE {
            get {
                return this.lINEField;
            }
            set {
                this.lINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LINESpecified {
            get {
                return this.lINEFieldSpecified;
            }
            set {
                this.lINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010Response_EMI {
        
        private RTTIE010Response_EMI_ENTITYMASTERINFO _ENTITYMASTERINFOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_ENTITY-MASTER-INFO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RTTIE010Response_EMI_ENTITYMASTERINFO _ENTITYMASTERINFO {
            get {
                return this._ENTITYMASTERINFOField;
            }
            set {
                this._ENTITYMASTERINFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010Response_EMI_ENTITYMASTERINFO {
        
        private string fUNCTIONCODEField;
        
        private decimal eNTITYTYPEField;
        
        private bool eNTITYTYPEFieldSpecified;
        
        private string eNTITYIDField;
        
        private string aCCOUNTIDField;
        
        private decimal nAICFEDERALCODEField;
        
        private bool nAICFEDERALCODEFieldSpecified;
        
        private decimal sICFEDERALCODEField;
        
        private bool sICFEDERALCODEFieldSpecified;
        
        private decimal bUSINESSSTARTDATEField;
        
        private bool bUSINESSSTARTDATEFieldSpecified;
        
        private decimal oRGANIZATIONTYPEField;
        
        private bool oRGANIZATIONTYPEFieldSpecified;
        
        private decimal bUSINESSORIGINField;
        
        private bool bUSINESSORIGINFieldSpecified;
        
        private string bUSINESSGENDERField;
        
        private string bUSINESSOTHERField;
        
        private decimal pINNUMBERField;
        
        private bool pINNUMBERFieldSpecified;
        
        private string pINSWITCHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ENTITYTYPE {
            get {
                return this.eNTITYTYPEField;
            }
            set {
                this.eNTITYTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENTITYTYPESpecified {
            get {
                return this.eNTITYTYPEFieldSpecified;
            }
            set {
                this.eNTITYTYPEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NAIC-FEDERAL-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NAICFEDERALCODE {
            get {
                return this.nAICFEDERALCODEField;
            }
            set {
                this.nAICFEDERALCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAICFEDERALCODESpecified {
            get {
                return this.nAICFEDERALCODEFieldSpecified;
            }
            set {
                this.nAICFEDERALCODEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SIC-FEDERAL-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SICFEDERALCODE {
            get {
                return this.sICFEDERALCODEField;
            }
            set {
                this.sICFEDERALCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SICFEDERALCODESpecified {
            get {
                return this.sICFEDERALCODEFieldSpecified;
            }
            set {
                this.sICFEDERALCODEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-START-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BUSINESSSTARTDATE {
            get {
                return this.bUSINESSSTARTDATEField;
            }
            set {
                this.bUSINESSSTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BUSINESSSTARTDATESpecified {
            get {
                return this.bUSINESSSTARTDATEFieldSpecified;
            }
            set {
                this.bUSINESSSTARTDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ORGANIZATION-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ORGANIZATIONTYPE {
            get {
                return this.oRGANIZATIONTYPEField;
            }
            set {
                this.oRGANIZATIONTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORGANIZATIONTYPESpecified {
            get {
                return this.oRGANIZATIONTYPEFieldSpecified;
            }
            set {
                this.oRGANIZATIONTYPEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-ORIGIN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BUSINESSORIGIN {
            get {
                return this.bUSINESSORIGINField;
            }
            set {
                this.bUSINESSORIGINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BUSINESSORIGINSpecified {
            get {
                return this.bUSINESSORIGINFieldSpecified;
            }
            set {
                this.bUSINESSORIGINFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-GENDER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSINESSGENDER {
            get {
                return this.bUSINESSGENDERField;
            }
            set {
                this.bUSINESSGENDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-OTHER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSINESSOTHER {
            get {
                return this.bUSINESSOTHERField;
            }
            set {
                this.bUSINESSOTHERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PIN-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PINNUMBER {
            get {
                return this.pINNUMBERField;
            }
            set {
                this.pINNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PINNUMBERSpecified {
            get {
                return this.pINNUMBERFieldSpecified;
            }
            set {
                this.pINNUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PIN-SWITCH", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PINSWITCH {
            get {
                return this.pINSWITCHField;
            }
            set {
                this.pINSWITCHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010Response_ETA {
        
        private RTTIE010Response_ETA_ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_ENTITY-TAX-ACCOUNTSs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_ENTITY-TAX-ACCOUNTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RTTIE010Response_ETA_ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSs {
            get {
                return this._ENTITYTAXACCOUNTSsField;
            }
            set {
                this._ENTITYTAXACCOUNTSsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010Response_ETA_ENTITYTAXACCOUNTS {
        
        private string fUNCTIONCODEField;
        
        private decimal aCCOUNTField;
        
        private bool aCCOUNTFieldSpecified;
        
        private decimal sTARTDATEField;
        
        private bool sTARTDATEFieldSpecified;
        
        private string wAGMONTHLYGROSSField;
        
        private RTTIE010Response_ETA_ENTITYTAXACCOUNTSBPTNEWAPPLICATION bPTNEWAPPLICATIONField;
        
        private string pRKIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ACCOUNT {
            get {
                return this.aCCOUNTField;
            }
            set {
                this.aCCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ACCOUNTSpecified {
            get {
                return this.aCCOUNTFieldSpecified;
            }
            set {
                this.aCCOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("START-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal STARTDATE {
            get {
                return this.sTARTDATEField;
            }
            set {
                this.sTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STARTDATESpecified {
            get {
                return this.sTARTDATEFieldSpecified;
            }
            set {
                this.sTARTDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WAG-MONTHLY-GROSS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WAGMONTHLYGROSS {
            get {
                return this.wAGMONTHLYGROSSField;
            }
            set {
                this.wAGMONTHLYGROSSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPT-NEW-APPLICATION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RTTIE010Response_ETA_ENTITYTAXACCOUNTSBPTNEWAPPLICATION BPTNEWAPPLICATION {
            get {
                return this.bPTNEWAPPLICATIONField;
            }
            set {
                this.bPTNEWAPPLICATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRK-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRKID {
            get {
                return this.pRKIDField;
            }
            set {
                this.pRKIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010Response_ETA_ENTITYTAXACCOUNTSBPTNEWAPPLICATION {
        
        private string bPTNAAPPLYFOREXEMPTIONField;
        
        private string bPTNAREACTIVATINGField;
        
        private string bPTNAAFFILIATEDField;
        
        private string bPTNANEWOWNERField;
        
        private string bPTNAREALESTATEField;
        
        private string bPTNAACCEPTEDField;
        
        private string bPTNACOMPLYYEAR1Field;
        
        private string bPTNACOMPLYYEAR2Field;
        
        private string bPTNASTATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-APPLY-FOR-EXEMPTION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNAAPPLYFOREXEMPTION {
            get {
                return this.bPTNAAPPLYFOREXEMPTIONField;
            }
            set {
                this.bPTNAAPPLYFOREXEMPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-REACTIVATING", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNAREACTIVATING {
            get {
                return this.bPTNAREACTIVATINGField;
            }
            set {
                this.bPTNAREACTIVATINGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-AFFILIATED", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNAAFFILIATED {
            get {
                return this.bPTNAAFFILIATEDField;
            }
            set {
                this.bPTNAAFFILIATEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-NEWOWNER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNANEWOWNER {
            get {
                return this.bPTNANEWOWNERField;
            }
            set {
                this.bPTNANEWOWNERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-REALESTATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNAREALESTATE {
            get {
                return this.bPTNAREALESTATEField;
            }
            set {
                this.bPTNAREALESTATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-ACCEPTED", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNAACCEPTED {
            get {
                return this.bPTNAACCEPTEDField;
            }
            set {
                this.bPTNAACCEPTEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-COMPLY-YEAR1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNACOMPLYYEAR1 {
            get {
                return this.bPTNACOMPLYYEAR1Field;
            }
            set {
                this.bPTNACOMPLYYEAR1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-COMPLY-YEAR2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNACOMPLYYEAR2 {
            get {
                return this.bPTNACOMPLYYEAR2Field;
            }
            set {
                this.bPTNACOMPLYYEAR2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTNA-STATUS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTNASTATUS {
            get {
                return this.bPTNASTATUSField;
            }
            set {
                this.bPTNASTATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010Response_ECHK {
        
        private RTTIE010Response_ECHK_ECHECK _ECHECKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_E-CHECK", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RTTIE010Response_ECHK_ECHECK _ECHECK {
            get {
                return this._ECHECKField;
            }
            set {
                this._ECHECKField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010Response_ECHK_ECHECK {
        
        private string fUNCTIONCODEField;
        
        private string tRANSITROUTINGNUMBERField;
        
        private string bANKACCOUNTNUMBERField;
        
        private string bANKACCOUNTTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TRANSIT-ROUTING-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANSITROUTINGNUMBER {
            get {
                return this.tRANSITROUTINGNUMBERField;
            }
            set {
                this.tRANSITROUTINGNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BANK-ACCOUNT-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANKACCOUNTNUMBER {
            get {
                return this.bANKACCOUNTNUMBERField;
            }
            set {
                this.bANKACCOUNTNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BANK-ACCOUNT-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANKACCOUNTTYPE {
            get {
                return this.bANKACCOUNTTYPEField;
            }
            set {
                this.bANKACCOUNTTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010Response_ENA1 {
        
        private RTTIE010Response_ENA1_NAMADDR1[] _NAMADDR1sField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_NAM-ADDR-1s", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_NAM-ADDR-1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RTTIE010Response_ENA1_NAMADDR1[] _NAMADDR1s {
            get {
                return this._NAMADDR1sField;
            }
            set {
                this._NAMADDR1sField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010Response_ENA1_NAMADDR1 {
        
        private string fUNCTIONCODEField;
        
        private decimal eNTITYTYPEField;
        
        private bool eNTITYTYPEFieldSpecified;
        
        private string eNTITYIDField;
        
        private string eNTITYNAMEField;
        
        private string tRADENAMEField;
        
        private decimal aDDRESSTYPEField;
        
        private bool aDDRESSTYPEFieldSpecified;
        
        private decimal rELATIONSHIPCODEField;
        
        private bool rELATIONSHIPCODEFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ENTITYTYPE {
            get {
                return this.eNTITYTYPEField;
            }
            set {
                this.eNTITYTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENTITYTYPESpecified {
            get {
                return this.eNTITYTYPEFieldSpecified;
            }
            set {
                this.eNTITYTYPEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYNAME {
            get {
                return this.eNTITYNAMEField;
            }
            set {
                this.eNTITYNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TRADE-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRADENAME {
            get {
                return this.tRADENAMEField;
            }
            set {
                this.tRADENAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ADDRESSTYPE {
            get {
                return this.aDDRESSTYPEField;
            }
            set {
                this.aDDRESSTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ADDRESSTYPESpecified {
            get {
                return this.aDDRESSTYPEFieldSpecified;
            }
            set {
                this.aDDRESSTYPEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RELATIONSHIP-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal RELATIONSHIPCODE {
            get {
                return this.rELATIONSHIPCODEField;
            }
            set {
                this.rELATIONSHIPCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RELATIONSHIPCODESpecified {
            get {
                return this.rELATIONSHIPCODEFieldSpecified;
            }
            set {
                this.rELATIONSHIPCODEFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010Response_ENA2 {
        
        private RTTIE010Response_ENA2_NAMADDR2[] _NAMADDR2sField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_NAM-ADDR-2s", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_NAM-ADDR-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RTTIE010Response_ENA2_NAMADDR2[] _NAMADDR2s {
            get {
                return this._NAMADDR2sField;
            }
            set {
                this._NAMADDR2sField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RTTIE010")]
    public partial class RTTIE010Response_ENA2_NAMADDR2 {
        
        private string aTTENTIONField;
        
        private string aDDRESSLINE1Field;
        
        private string aDDRESSLINE2Field;
        
        private string cITYField;
        
        private string sTATEField;
        
        private string zIPCODEField;
        
        private decimal bUSINESSPHONENUMBERField;
        
        private bool bUSINESSPHONENUMBERFieldSpecified;
        
        private string bUSINESSPHONEEXTENSIONField;
        
        private decimal bUSINESSFAXField;
        
        private bool bUSINESSFAXFieldSpecified;
        
        private decimal oTHERPHONENUMBERField;
        
        private bool oTHERPHONENUMBERFieldSpecified;
        
        private string eMAILADDRField;
        
        private decimal tINAMSEQUENCENUMBERField;
        
        private bool tINAMSEQUENCENUMBERFieldSpecified;
        
        private decimal tIADRSEQUENCENUMBERField;
        
        private bool tIADRSEQUENCENUMBERFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATTENTION {
            get {
                return this.aTTENTIONField;
            }
            set {
                this.aTTENTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE-1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRESSLINE1 {
            get {
                return this.aDDRESSLINE1Field;
            }
            set {
                this.aDDRESSLINE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRESSLINE2 {
            get {
                return this.aDDRESSLINE2Field;
            }
            set {
                this.aDDRESSLINE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZIP-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIPCODE {
            get {
                return this.zIPCODEField;
            }
            set {
                this.zIPCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-PHONE-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BUSINESSPHONENUMBER {
            get {
                return this.bUSINESSPHONENUMBERField;
            }
            set {
                this.bUSINESSPHONENUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BUSINESSPHONENUMBERSpecified {
            get {
                return this.bUSINESSPHONENUMBERFieldSpecified;
            }
            set {
                this.bUSINESSPHONENUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-PHONE-EXTENSION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSINESSPHONEEXTENSION {
            get {
                return this.bUSINESSPHONEEXTENSIONField;
            }
            set {
                this.bUSINESSPHONEEXTENSIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BUSINESS-FAX", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BUSINESSFAX {
            get {
                return this.bUSINESSFAXField;
            }
            set {
                this.bUSINESSFAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BUSINESSFAXSpecified {
            get {
                return this.bUSINESSFAXFieldSpecified;
            }
            set {
                this.bUSINESSFAXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OTHER-PHONE-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal OTHERPHONENUMBER {
            get {
                return this.oTHERPHONENUMBERField;
            }
            set {
                this.oTHERPHONENUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OTHERPHONENUMBERSpecified {
            get {
                return this.oTHERPHONENUMBERFieldSpecified;
            }
            set {
                this.oTHERPHONENUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("E-MAIL-ADDR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMAILADDR {
            get {
                return this.eMAILADDRField;
            }
            set {
                this.eMAILADDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TINAM-SEQUENCE-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TINAMSEQUENCENUMBER {
            get {
                return this.tINAMSEQUENCENUMBERField;
            }
            set {
                this.tINAMSEQUENCENUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TINAMSEQUENCENUMBERSpecified {
            get {
                return this.tINAMSEQUENCENUMBERFieldSpecified;
            }
            set {
                this.tINAMSEQUENCENUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TIADR-SEQUENCE-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TIADRSEQUENCENUMBER {
            get {
                return this.tIADRSEQUENCENUMBERField;
            }
            set {
                this.tIADRSEQUENCENUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TIADRSEQUENCENUMBERSpecified {
            get {
                return this.tIADRSEQUENCENUMBERFieldSpecified;
            }
            set {
                this.tIADRSEQUENCENUMBERFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallRTTIE010CompletedEventHandler(object sender, CallRTTIE010CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallRTTIE010CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallRTTIE010CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RTTIE010Response_SMA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RTTIE010Response_SMA)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public RTTIE010Response_EMI _EMI1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RTTIE010Response_EMI)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public RTTIE010Response_ETA _ETA1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RTTIE010Response_ETA)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public RTTIE010Response_ECHK _ECHK1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RTTIE010Response_ECHK)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public RTTIE010Response_ENA1 _ENA11 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RTTIE010Response_ENA1)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public RTTIE010Response_ENA2 _ENA21 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RTTIE010Response_ENA2)(this.results[5]));
            }
        }
    }
}

#pragma warning restore 1591