//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace CopRevenueGov2.WAGE_RTTIE027_SrvRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TIPSACCDSOAP11Binding", Namespace="http://namespace.softwareag.com/entirex/xml/mapping")]
    public partial class RT01E027 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallRT01E027OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RT01E027() {
            this.Url = "http://istest.city.phila.local:10010/wsstack/services/RT01E027.TIPSACCDSOAP11Port" +
                "/";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallRT01E027CompletedEventHandler CallRT01E027Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RT01E027", RequestElementName="RT01E027", RequestNamespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RT01E027", ResponseElementName="RT01E027Response", ResponseNamespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RT01E027", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_SMA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RT01E027Response_SMA CallRT01E027([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] RT01E027_SMA _SMA, [System.Xml.Serialization.XmlElementAttribute("_E-WAG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] RT01E027_EWAG _EWAG, [System.Xml.Serialization.XmlElementAttribute("_E-AMT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] RT01E027_EAMT _EAMT, [System.Xml.Serialization.XmlElementAttribute("_E-WAG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out RT01E027Response_EWAG _EWAG1, [System.Xml.Serialization.XmlElementAttribute("_E-AMT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out RT01E027Response_EAMT _EAMT1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out RT01E027Response_SERR _SERR) {
            object[] results = this.Invoke("CallRT01E027", new object[] {
                        _SMA,
                        _EWAG,
                        _EAMT});
            _EWAG1 = ((RT01E027Response_EWAG)(results[1]));
            _EAMT1 = ((RT01E027Response_EAMT)(results[2]));
            _SERR = ((RT01E027Response_SERR)(results[3]));
            return ((RT01E027Response_SMA)(results[0]));
        }
        
        /// <remarks/>
        public void CallRT01E027Async(RT01E027_SMA _SMA, RT01E027_EWAG _EWAG, RT01E027_EAMT _EAMT) {
            this.CallRT01E027Async(_SMA, _EWAG, _EAMT, null);
        }
        
        /// <remarks/>
        public void CallRT01E027Async(RT01E027_SMA _SMA, RT01E027_EWAG _EWAG, RT01E027_EAMT _EAMT, object userState) {
            if ((this.CallRT01E027OperationCompleted == null)) {
                this.CallRT01E027OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallRT01E027OperationCompleted);
            }
            this.InvokeAsync("CallRT01E027", new object[] {
                        _SMA,
                        _EWAG,
                        _EAMT}, this.CallRT01E027OperationCompleted, userState);
        }
        
        private void OnCallRT01E027OperationCompleted(object arg) {
            if ((this.CallRT01E027Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallRT01E027Completed(this, new CallRT01E027CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RT01E027")]
    public partial class RT01E027_SMA {
        
        private string _PROGRAMField;
        
        private decimal sYSTEMERRORField;
        
        private bool sYSTEMERRORFieldSpecified;
        
        private decimal eRRORLINEField;
        
        private bool eRRORLINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SYSTEM-ERROR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SYSTEMERROR {
            get {
                return this.sYSTEMERRORField;
            }
            set {
                this.sYSTEMERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SYSTEMERRORSpecified {
            get {
                return this.sYSTEMERRORFieldSpecified;
            }
            set {
                this.sYSTEMERRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERROR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERRORLINE {
            get {
                return this.eRRORLINEField;
            }
            set {
                this.eRRORLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORLINESpecified {
            get {
                return this.eRRORLINEFieldSpecified;
            }
            set {
                this.eRRORLINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RT01E027")]
    public partial class RT01E027_EWAG {
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string vERSIONXField;
        
        private string dOCUMENTCONTROLXField;
        
        private string aDJREFNOField;
        
        private string fEDERALIDNUMBERField;
        
        private string rETURNSTATUSField;
        
        private string sEQUENCENUMField;
        
        private string lASTUPDATEDATEXField;
        
        private string nUMBEROFRESIDENTSXField;
        
        private string nUMBEROFNONRESIDENTSXField;
        
        private string pHILAEMPLOYEESXField;
        
        private string tOTALEMPLOYEESXField;
        
        private string rESRATEAField;
        
        private string rESRATEBField;
        
        private string nONRATEAField;
        
        private string nONRATEBField;
        
        private string fREQUENCYField;
        
        private string dUEDATEField;
        
        private string pREPARERNAMEField;
        
        private decimal pREPARERPHONEField;
        
        private bool pREPARERPHONEFieldSpecified;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILADDRESSField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VERSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VERSIONX {
            get {
                return this.vERSIONXField;
            }
            set {
                this.vERSIONXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DOCUMENT-CONTROL-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOCUMENTCONTROLX {
            get {
                return this.dOCUMENTCONTROLXField;
            }
            set {
                this.dOCUMENTCONTROLXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJ-REFNO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADJREFNO {
            get {
                return this.aDJREFNOField;
            }
            set {
                this.aDJREFNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FEDERAL-ID-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FEDERALIDNUMBER {
            get {
                return this.fEDERALIDNUMBERField;
            }
            set {
                this.fEDERALIDNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RETURN-STATUS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETURNSTATUS {
            get {
                return this.rETURNSTATUSField;
            }
            set {
                this.rETURNSTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SEQUENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEQUENCENUM {
            get {
                return this.sEQUENCENUMField;
            }
            set {
                this.sEQUENCENUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LAST-UPDATE-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LASTUPDATEDATEX {
            get {
                return this.lASTUPDATEDATEXField;
            }
            set {
                this.lASTUPDATEDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NUMBER-OF-RESIDENTS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMBEROFRESIDENTSX {
            get {
                return this.nUMBEROFRESIDENTSXField;
            }
            set {
                this.nUMBEROFRESIDENTSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NUMBER-OF-NON-RESIDENTS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMBEROFNONRESIDENTSX {
            get {
                return this.nUMBEROFNONRESIDENTSXField;
            }
            set {
                this.nUMBEROFNONRESIDENTSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PHILA-EMPLOYEES-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PHILAEMPLOYEESX {
            get {
                return this.pHILAEMPLOYEESXField;
            }
            set {
                this.pHILAEMPLOYEESXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-EMPLOYEES-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALEMPLOYEESX {
            get {
                return this.tOTALEMPLOYEESXField;
            }
            set {
                this.tOTALEMPLOYEESXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-RATE-A", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESRATEA {
            get {
                return this.rESRATEAField;
            }
            set {
                this.rESRATEAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-RATE-B", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESRATEB {
            get {
                return this.rESRATEBField;
            }
            set {
                this.rESRATEBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RATE-A", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRATEA {
            get {
                return this.nONRATEAField;
            }
            set {
                this.nONRATEAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RATE-B", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRATEB {
            get {
                return this.nONRATEBField;
            }
            set {
                this.nONRATEBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DUE-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DUEDATE {
            get {
                return this.dUEDATEField;
            }
            set {
                this.dUEDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PREPARERPHONESpecified {
            get {
                return this.pREPARERPHONEFieldSpecified;
            }
            set {
                this.pREPARERPHONEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPAREREMAILADDRESS {
            get {
                return this.pREPAREREMAILADDRESSField;
            }
            set {
                this.pREPAREREMAILADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RT01E027")]
    public partial class RT01E027_EAMT {
        
        private string gROSSCOMPENSATIONXField;
        
        private string nONTAXABLECOMPXField;
        
        private string tIPSWAGESXField;
        
        private string nETCOMPENSATIONXField;
        
        private string rESIDENTPAYROLLAXField;
        
        private string rESIDENTTAXDUEAXField;
        
        private string rESIDENTPAYROLLBXField;
        
        private string rESIDENTTAXDUEBXField;
        
        private string nONRESPAYROLLAXField;
        
        private string nONRESTAXDUEAXField;
        
        private string nONRESPAYROLLBXField;
        
        private string nONRESTAXDUEBXField;
        
        private string tOTALGROSSTAXDUEXField;
        
        private string tAXPAIDXField;
        
        private string tAXDUEXField;
        
        private string tAXOVERPAIDXField;
        
        private string pOSTINGDATEXField;
        
        private string fILINGDATEXField;
        
        private string uSERIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GROSS-COMPENSATION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GROSSCOMPENSATIONX {
            get {
                return this.gROSSCOMPENSATIONXField;
            }
            set {
                this.gROSSCOMPENSATIONXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-TAXABLE-COMP-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONTAXABLECOMPX {
            get {
                return this.nONTAXABLECOMPXField;
            }
            set {
                this.nONTAXABLECOMPXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TIPS-WAGES-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIPSWAGESX {
            get {
                return this.tIPSWAGESXField;
            }
            set {
                this.tIPSWAGESXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-COMPENSATION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETCOMPENSATIONX {
            get {
                return this.nETCOMPENSATIONXField;
            }
            set {
                this.nETCOMPENSATIONXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-PAYROLL-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESIDENTPAYROLLAX {
            get {
                return this.rESIDENTPAYROLLAXField;
            }
            set {
                this.rESIDENTPAYROLLAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-TAX-DUE-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESIDENTTAXDUEAX {
            get {
                return this.rESIDENTTAXDUEAXField;
            }
            set {
                this.rESIDENTTAXDUEAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-PAYROLL-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESIDENTPAYROLLBX {
            get {
                return this.rESIDENTPAYROLLBXField;
            }
            set {
                this.rESIDENTPAYROLLBXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-TAX-DUE-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESIDENTTAXDUEBX {
            get {
                return this.rESIDENTTAXDUEBXField;
            }
            set {
                this.rESIDENTTAXDUEBXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-PAYROLL-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESPAYROLLAX {
            get {
                return this.nONRESPAYROLLAXField;
            }
            set {
                this.nONRESPAYROLLAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-TAX-DUE-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESTAXDUEAX {
            get {
                return this.nONRESTAXDUEAXField;
            }
            set {
                this.nONRESTAXDUEAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-PAYROLL-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESPAYROLLBX {
            get {
                return this.nONRESPAYROLLBXField;
            }
            set {
                this.nONRESPAYROLLBXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-TAX-DUE-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESTAXDUEBX {
            get {
                return this.nONRESTAXDUEBXField;
            }
            set {
                this.nONRESTAXDUEBXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-GROSS-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALGROSSTAXDUEX {
            get {
                return this.tOTALGROSSTAXDUEXField;
            }
            set {
                this.tOTALGROSSTAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-PAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXPAIDX {
            get {
                return this.tAXPAIDXField;
            }
            set {
                this.tAXPAIDXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXDUEX {
            get {
                return this.tAXDUEXField;
            }
            set {
                this.tAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-OVERPAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXOVERPAIDX {
            get {
                return this.tAXOVERPAIDXField;
            }
            set {
                this.tAXOVERPAIDXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POSTING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POSTINGDATEX {
            get {
                return this.pOSTINGDATEXField;
            }
            set {
                this.pOSTINGDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FILING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FILINGDATEX {
            get {
                return this.fILINGDATEXField;
            }
            set {
                this.fILINGDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RT01E027")]
    public partial class RT01E027Response_SMA {
        
        private string _PROGRAMField;
        
        private decimal sYSTEMERRORField;
        
        private bool sYSTEMERRORFieldSpecified;
        
        private decimal eRRORLINEField;
        
        private bool eRRORLINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SYSTEM-ERROR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SYSTEMERROR {
            get {
                return this.sYSTEMERRORField;
            }
            set {
                this.sYSTEMERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SYSTEMERRORSpecified {
            get {
                return this.sYSTEMERRORFieldSpecified;
            }
            set {
                this.sYSTEMERRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERROR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERRORLINE {
            get {
                return this.eRRORLINEField;
            }
            set {
                this.eRRORLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORLINESpecified {
            get {
                return this.eRRORLINEFieldSpecified;
            }
            set {
                this.eRRORLINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RT01E027")]
    public partial class RT01E027Response_EWAG {
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string vERSIONXField;
        
        private string dOCUMENTCONTROLXField;
        
        private string aDJREFNOField;
        
        private string fEDERALIDNUMBERField;
        
        private string rETURNSTATUSField;
        
        private string sEQUENCENUMField;
        
        private string lASTUPDATEDATEXField;
        
        private string nUMBEROFRESIDENTSXField;
        
        private string nUMBEROFNONRESIDENTSXField;
        
        private string pHILAEMPLOYEESXField;
        
        private string tOTALEMPLOYEESXField;
        
        private string rESRATEAField;
        
        private string rESRATEBField;
        
        private string nONRATEAField;
        
        private string nONRATEBField;
        
        private string fREQUENCYField;
        
        private string dUEDATEField;
        
        private string pREPARERNAMEField;
        
        private decimal pREPARERPHONEField;
        
        private bool pREPARERPHONEFieldSpecified;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILADDRESSField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VERSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VERSIONX {
            get {
                return this.vERSIONXField;
            }
            set {
                this.vERSIONXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DOCUMENT-CONTROL-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOCUMENTCONTROLX {
            get {
                return this.dOCUMENTCONTROLXField;
            }
            set {
                this.dOCUMENTCONTROLXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJ-REFNO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADJREFNO {
            get {
                return this.aDJREFNOField;
            }
            set {
                this.aDJREFNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FEDERAL-ID-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FEDERALIDNUMBER {
            get {
                return this.fEDERALIDNUMBERField;
            }
            set {
                this.fEDERALIDNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RETURN-STATUS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETURNSTATUS {
            get {
                return this.rETURNSTATUSField;
            }
            set {
                this.rETURNSTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SEQUENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEQUENCENUM {
            get {
                return this.sEQUENCENUMField;
            }
            set {
                this.sEQUENCENUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LAST-UPDATE-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LASTUPDATEDATEX {
            get {
                return this.lASTUPDATEDATEXField;
            }
            set {
                this.lASTUPDATEDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NUMBER-OF-RESIDENTS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMBEROFRESIDENTSX {
            get {
                return this.nUMBEROFRESIDENTSXField;
            }
            set {
                this.nUMBEROFRESIDENTSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NUMBER-OF-NON-RESIDENTS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMBEROFNONRESIDENTSX {
            get {
                return this.nUMBEROFNONRESIDENTSXField;
            }
            set {
                this.nUMBEROFNONRESIDENTSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PHILA-EMPLOYEES-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PHILAEMPLOYEESX {
            get {
                return this.pHILAEMPLOYEESXField;
            }
            set {
                this.pHILAEMPLOYEESXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-EMPLOYEES-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALEMPLOYEESX {
            get {
                return this.tOTALEMPLOYEESXField;
            }
            set {
                this.tOTALEMPLOYEESXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-RATE-A", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESRATEA {
            get {
                return this.rESRATEAField;
            }
            set {
                this.rESRATEAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-RATE-B", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESRATEB {
            get {
                return this.rESRATEBField;
            }
            set {
                this.rESRATEBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RATE-A", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRATEA {
            get {
                return this.nONRATEAField;
            }
            set {
                this.nONRATEAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RATE-B", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRATEB {
            get {
                return this.nONRATEBField;
            }
            set {
                this.nONRATEBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DUE-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DUEDATE {
            get {
                return this.dUEDATEField;
            }
            set {
                this.dUEDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PREPARERPHONESpecified {
            get {
                return this.pREPARERPHONEFieldSpecified;
            }
            set {
                this.pREPARERPHONEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPAREREMAILADDRESS {
            get {
                return this.pREPAREREMAILADDRESSField;
            }
            set {
                this.pREPAREREMAILADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RT01E027")]
    public partial class RT01E027Response_EAMT {
        
        private string gROSSCOMPENSATIONXField;
        
        private string nONTAXABLECOMPXField;
        
        private string tIPSWAGESXField;
        
        private string nETCOMPENSATIONXField;
        
        private string rESIDENTPAYROLLAXField;
        
        private string rESIDENTTAXDUEAXField;
        
        private string rESIDENTPAYROLLBXField;
        
        private string rESIDENTTAXDUEBXField;
        
        private string nONRESPAYROLLAXField;
        
        private string nONRESTAXDUEAXField;
        
        private string nONRESPAYROLLBXField;
        
        private string nONRESTAXDUEBXField;
        
        private string tOTALGROSSTAXDUEXField;
        
        private string tAXPAIDXField;
        
        private string tAXDUEXField;
        
        private string tAXOVERPAIDXField;
        
        private string pOSTINGDATEXField;
        
        private string fILINGDATEXField;
        
        private string uSERIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GROSS-COMPENSATION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GROSSCOMPENSATIONX {
            get {
                return this.gROSSCOMPENSATIONXField;
            }
            set {
                this.gROSSCOMPENSATIONXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-TAXABLE-COMP-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONTAXABLECOMPX {
            get {
                return this.nONTAXABLECOMPXField;
            }
            set {
                this.nONTAXABLECOMPXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TIPS-WAGES-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIPSWAGESX {
            get {
                return this.tIPSWAGESXField;
            }
            set {
                this.tIPSWAGESXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-COMPENSATION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETCOMPENSATIONX {
            get {
                return this.nETCOMPENSATIONXField;
            }
            set {
                this.nETCOMPENSATIONXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-PAYROLL-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESIDENTPAYROLLAX {
            get {
                return this.rESIDENTPAYROLLAXField;
            }
            set {
                this.rESIDENTPAYROLLAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-TAX-DUE-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESIDENTTAXDUEAX {
            get {
                return this.rESIDENTTAXDUEAXField;
            }
            set {
                this.rESIDENTTAXDUEAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-PAYROLL-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESIDENTPAYROLLBX {
            get {
                return this.rESIDENTPAYROLLBXField;
            }
            set {
                this.rESIDENTPAYROLLBXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESIDENT-TAX-DUE-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESIDENTTAXDUEBX {
            get {
                return this.rESIDENTTAXDUEBXField;
            }
            set {
                this.rESIDENTTAXDUEBXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-PAYROLL-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESPAYROLLAX {
            get {
                return this.nONRESPAYROLLAXField;
            }
            set {
                this.nONRESPAYROLLAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-TAX-DUE-A-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESTAXDUEAX {
            get {
                return this.nONRESTAXDUEAXField;
            }
            set {
                this.nONRESTAXDUEAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-PAYROLL-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESPAYROLLBX {
            get {
                return this.nONRESPAYROLLBXField;
            }
            set {
                this.nONRESPAYROLLBXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-TAX-DUE-B-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESTAXDUEBX {
            get {
                return this.nONRESTAXDUEBXField;
            }
            set {
                this.nONRESTAXDUEBXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-GROSS-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALGROSSTAXDUEX {
            get {
                return this.tOTALGROSSTAXDUEXField;
            }
            set {
                this.tOTALGROSSTAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-PAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXPAIDX {
            get {
                return this.tAXPAIDXField;
            }
            set {
                this.tAXPAIDXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXDUEX {
            get {
                return this.tAXDUEXField;
            }
            set {
                this.tAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-OVERPAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXOVERPAIDX {
            get {
                return this.tAXOVERPAIDXField;
            }
            set {
                this.tAXOVERPAIDXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POSTING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POSTINGDATEX {
            get {
                return this.pOSTINGDATEXField;
            }
            set {
                this.pOSTINGDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FILING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FILINGDATEX {
            get {
                return this.fILINGDATEXField;
            }
            set {
                this.fILINGDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD-RT01E027")]
    public partial class RT01E027Response_SERR {
        
        private string _SERRPROGRAMField;
        
        private decimal _SERRNUMBERField;
        
        private bool _SERRNUMBERFieldSpecified;
        
        private decimal _SERRLINEField;
        
        private bool _SERRLINEFieldSpecified;
        
        private string _SERRDATEField;
        
        private string _SERRTIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-PROGRAM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _SERRPROGRAM {
            get {
                return this._SERRPROGRAMField;
            }
            set {
                this._SERRPROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal _SERRNUMBER {
            get {
                return this._SERRNUMBERField;
            }
            set {
                this._SERRNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _SERRNUMBERSpecified {
            get {
                return this._SERRNUMBERFieldSpecified;
            }
            set {
                this._SERRNUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal _SERRLINE {
            get {
                return this._SERRLINEField;
            }
            set {
                this._SERRLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _SERRLINESpecified {
            get {
                return this._SERRLINEFieldSpecified;
            }
            set {
                this._SERRLINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _SERRDATE {
            get {
                return this._SERRDATEField;
            }
            set {
                this._SERRDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-TIME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _SERRTIME {
            get {
                return this._SERRTIMEField;
            }
            set {
                this._SERRTIMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallRT01E027CompletedEventHandler(object sender, CallRT01E027CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallRT01E027CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallRT01E027CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RT01E027Response_SMA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RT01E027Response_SMA)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public RT01E027Response_EWAG _EWAG1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RT01E027Response_EWAG)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public RT01E027Response_EAMT _EAMT1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RT01E027Response_EAMT)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public RT01E027Response_SERR _SERR {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RT01E027Response_SERR)(this.results[3]));
            }
        }
    }
}

#pragma warning restore 1591