//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopRevenueGov2.RTTIE222_SrvRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS", ConfigurationName="RTTIE222_SrvRef.RTTIE222WS_PortType")]
    public interface RTTIE222WS_PortType {
        
        // CODEGEN: Generating message contract since message part namespace (urn:com-softwareag-entirex-rpc:TIPSACCD) does not match the default value (http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS)
        [System.ServiceModel.OperationContractAttribute(Action="RTTIE222_service_RTTIE222WS_Binder_RTTIE2222", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RTTIE222Response")]
        CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Response RTTIE2222(CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RTTIE222_service_RTTIE222WS_Binder_RTTIE2222", ReplyAction="*")]
        System.Threading.Tasks.Task<CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Response> RTTIE2222Async(CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
    public partial class RTTIE222 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _SMA _SMAField;
        
        private _EMI _EMIField;
        
        private _ETA _ETAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public _SMA _SMA {
            get {
                return this._SMAField;
            }
            set {
                this._SMAField = value;
                this.RaisePropertyChanged("_SMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public _EMI _EMI {
            get {
                return this._EMIField;
            }
            set {
                this._EMIField = value;
                this.RaisePropertyChanged("_EMI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public _ETA _ETA {
            get {
                return this._ETAField;
            }
            set {
                this._ETAField = value;
                this.RaisePropertyChanged("_ETA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS")]
    public partial class _SMA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SYSTEM-MESSAGE-AREA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public _SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREA {
            get {
                return this._SYSTEMMESSAGEAREAField;
            }
            set {
                this._SYSTEMMESSAGEAREAField = value;
                this.RaisePropertyChanged("_SYSTEMMESSAGEAREA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_SYSTEM-MESSAGE-AREA", Namespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS")]
    public partial class _SYSTEMMESSAGEAREA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _PROGRAMField;
        
        private System.Nullable<decimal> eRRORField;
        
        private bool eRRORFieldSpecified;
        
        private System.Nullable<decimal> lINEField;
        
        private bool lINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
                this.RaisePropertyChanged("_PROGRAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<decimal> ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORSpecified {
            get {
                return this.eRRORFieldSpecified;
            }
            set {
                this.eRRORFieldSpecified = value;
                this.RaisePropertyChanged("ERRORSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<decimal> LINE {
            get {
                return this.lINEField;
            }
            set {
                this.lINEField = value;
                this.RaisePropertyChanged("LINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LINESpecified {
            get {
                return this.lINEFieldSpecified;
            }
            set {
                this.lINEFieldSpecified = value;
                this.RaisePropertyChanged("LINESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_ENTITY-TAX-ACCOUNTS2", Namespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS")]
    public partial class _ENTITYTAXACCOUNTS2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fUNCTIONCODEField;
        
        private string aCCOUNTField;
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string pRINCIPALXField;
        
        private string iNTERESTXField;
        
        private string pENALTYXField;
        
        private string oTHERXField;
        
        private string bRTENTITYField;
        
        private string bRTADDRESSField;
        
        private string fILLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
                this.RaisePropertyChanged("FUNCTIONCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ACCOUNT {
            get {
                return this.aCCOUNTField;
            }
            set {
                this.aCCOUNTField = value;
                this.RaisePropertyChanged("ACCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
                this.RaisePropertyChanged("ACCOUNTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
                this.RaisePropertyChanged("PERIODX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRINCIPAL-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PRINCIPALX {
            get {
                return this.pRINCIPALXField;
            }
            set {
                this.pRINCIPALXField = value;
                this.RaisePropertyChanged("PRINCIPALX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INTEREST-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string INTERESTX {
            get {
                return this.iNTERESTXField;
            }
            set {
                this.iNTERESTXField = value;
                this.RaisePropertyChanged("INTERESTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PENALTY-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PENALTYX {
            get {
                return this.pENALTYXField;
            }
            set {
                this.pENALTYXField = value;
                this.RaisePropertyChanged("PENALTYX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OTHER-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string OTHERX {
            get {
                return this.oTHERXField;
            }
            set {
                this.oTHERXField = value;
                this.RaisePropertyChanged("OTHERX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ENTITY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string BRTENTITY {
            get {
                return this.bRTENTITYField;
            }
            set {
                this.bRTENTITYField = value;
                this.RaisePropertyChanged("BRTENTITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string BRTADDRESS {
            get {
                return this.bRTADDRESSField;
            }
            set {
                this.bRTADDRESSField = value;
                this.RaisePropertyChanged("BRTADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string FILL {
            get {
                return this.fILLField;
            }
            set {
                this.fILLField = value;
                this.RaisePropertyChanged("FILL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS")]
    public partial class _ETA2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _ENTITYTAXACCOUNTS2[] _ENTITYTAXACCOUNTSsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_ENTITY-TAX-ACCOUNTSs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_ENTITY-TAX-ACCOUNTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public _ENTITYTAXACCOUNTS2[] _ENTITYTAXACCOUNTSs {
            get {
                return this._ENTITYTAXACCOUNTSsField;
            }
            set {
                this._ENTITYTAXACCOUNTSsField = value;
                this.RaisePropertyChanged("_ENTITYTAXACCOUNTSs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_ENTITY-MASTER-INFO2", Namespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS")]
    public partial class _ENTITYMASTERINFO2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal eNTITYTYPEField;
        
        private string eNTITYIDField;
        
        private string fUNCTIONField;
        
        private string nOTICENUMField;
        
        private string nEXTACCOUNTField;
        
        private string nEXTACCOUNTIDField;
        
        private string nEXTPERIODField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal ENTITYTYPE {
            get {
                return this.eNTITYTYPEField;
            }
            set {
                this.eNTITYTYPEField = value;
                this.RaisePropertyChanged("ENTITYTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
                this.RaisePropertyChanged("ENTITYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FUNCTION {
            get {
                return this.fUNCTIONField;
            }
            set {
                this.fUNCTIONField = value;
                this.RaisePropertyChanged("FUNCTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NOTICE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NOTICENUM {
            get {
                return this.nOTICENUMField;
            }
            set {
                this.nOTICENUMField = value;
                this.RaisePropertyChanged("NOTICENUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NEXT-ACCOUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NEXTACCOUNT {
            get {
                return this.nEXTACCOUNTField;
            }
            set {
                this.nEXTACCOUNTField = value;
                this.RaisePropertyChanged("NEXTACCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NEXT-ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string NEXTACCOUNTID {
            get {
                return this.nEXTACCOUNTIDField;
            }
            set {
                this.nEXTACCOUNTIDField = value;
                this.RaisePropertyChanged("NEXTACCOUNTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NEXT-PERIOD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NEXTPERIOD {
            get {
                return this.nEXTPERIODField;
            }
            set {
                this.nEXTPERIODField = value;
                this.RaisePropertyChanged("NEXTPERIOD");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS")]
    public partial class _EMI2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _ENTITYMASTERINFO2 _ENTITYMASTERINFOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_ENTITY-MASTER-INFO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public _ENTITYMASTERINFO2 _ENTITYMASTERINFO {
            get {
                return this._ENTITYMASTERINFOField;
            }
            set {
                this._ENTITYMASTERINFOField = value;
                this.RaisePropertyChanged("_ENTITYMASTERINFO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_SYSTEM-MESSAGE-AREA2", Namespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS")]
    public partial class _SYSTEMMESSAGEAREA2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _PROGRAMField;
        
        private decimal eRRORField;
        
        private decimal lINEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
                this.RaisePropertyChanged("_PROGRAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal LINE {
            get {
                return this.lINEField;
            }
            set {
                this.lINEField = value;
                this.RaisePropertyChanged("LINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS")]
    public partial class _SMA2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _SYSTEMMESSAGEAREA2 _SYSTEMMESSAGEAREAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SYSTEM-MESSAGE-AREA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public _SYSTEMMESSAGEAREA2 _SYSTEMMESSAGEAREA {
            get {
                return this._SYSTEMMESSAGEAREAField;
            }
            set {
                this._SYSTEMMESSAGEAREAField = value;
                this.RaisePropertyChanged("_SYSTEMMESSAGEAREA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
    public partial class RTTIE222Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _SMA2 _SMAField;
        
        private _EMI2 _EMIField;
        
        private _ETA2 _ETAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public _SMA2 _SMA {
            get {
                return this._SMAField;
            }
            set {
                this._SMAField = value;
                this.RaisePropertyChanged("_SMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public _EMI2 _EMI {
            get {
                return this._EMIField;
            }
            set {
                this._EMIField = value;
                this.RaisePropertyChanged("_EMI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public _ETA2 _ETA {
            get {
                return this._ETAField;
            }
            set {
                this._ETAField = value;
                this.RaisePropertyChanged("_ETA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_ENTITY-TAX-ACCOUNTS", Namespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS")]
    public partial class _ENTITYTAXACCOUNTS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fUNCTIONCODEField;
        
        private string aCCOUNTField;
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string pRINCIPALXField;
        
        private string iNTERESTXField;
        
        private string pENALTYXField;
        
        private string oTHERXField;
        
        private string bRTENTITYField;
        
        private string bRTADDRESSField;
        
        private string fILLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
                this.RaisePropertyChanged("FUNCTIONCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string ACCOUNT {
            get {
                return this.aCCOUNTField;
            }
            set {
                this.aCCOUNTField = value;
                this.RaisePropertyChanged("ACCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
                this.RaisePropertyChanged("ACCOUNTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
                this.RaisePropertyChanged("PERIODX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRINCIPAL-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string PRINCIPALX {
            get {
                return this.pRINCIPALXField;
            }
            set {
                this.pRINCIPALXField = value;
                this.RaisePropertyChanged("PRINCIPALX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INTEREST-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string INTERESTX {
            get {
                return this.iNTERESTXField;
            }
            set {
                this.iNTERESTXField = value;
                this.RaisePropertyChanged("INTERESTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PENALTY-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string PENALTYX {
            get {
                return this.pENALTYXField;
            }
            set {
                this.pENALTYXField = value;
                this.RaisePropertyChanged("PENALTYX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OTHER-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string OTHERX {
            get {
                return this.oTHERXField;
            }
            set {
                this.oTHERXField = value;
                this.RaisePropertyChanged("OTHERX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ENTITY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string BRTENTITY {
            get {
                return this.bRTENTITYField;
            }
            set {
                this.bRTENTITYField = value;
                this.RaisePropertyChanged("BRTENTITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string BRTADDRESS {
            get {
                return this.bRTADDRESSField;
            }
            set {
                this.bRTADDRESSField = value;
                this.RaisePropertyChanged("BRTADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string FILL {
            get {
                return this.fILLField;
            }
            set {
                this.fILLField = value;
                this.RaisePropertyChanged("FILL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS")]
    public partial class _ETA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_ENTITY-TAX-ACCOUNTSs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public _ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSs {
            get {
                return this._ENTITYTAXACCOUNTSsField;
            }
            set {
                this._ENTITYTAXACCOUNTSsField = value;
                this.RaisePropertyChanged("_ENTITYTAXACCOUNTSs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="_ENTITY-MASTER-INFO", Namespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS")]
    public partial class _ENTITYMASTERINFO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> eNTITYTYPEField;
        
        private bool eNTITYTYPEFieldSpecified;
        
        private string eNTITYIDField;
        
        private string fUNCTIONField;
        
        private string nOTICENUMField;
        
        private string nEXTACCOUNTField;
        
        private string nEXTACCOUNTIDField;
        
        private string nEXTPERIODField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<decimal> ENTITYTYPE {
            get {
                return this.eNTITYTYPEField;
            }
            set {
                this.eNTITYTYPEField = value;
                this.RaisePropertyChanged("ENTITYTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENTITYTYPESpecified {
            get {
                return this.eNTITYTYPEFieldSpecified;
            }
            set {
                this.eNTITYTYPEFieldSpecified = value;
                this.RaisePropertyChanged("ENTITYTYPESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
                this.RaisePropertyChanged("ENTITYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string FUNCTION {
            get {
                return this.fUNCTIONField;
            }
            set {
                this.fUNCTIONField = value;
                this.RaisePropertyChanged("FUNCTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NOTICE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string NOTICENUM {
            get {
                return this.nOTICENUMField;
            }
            set {
                this.nOTICENUMField = value;
                this.RaisePropertyChanged("NOTICENUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NEXT-ACCOUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string NEXTACCOUNT {
            get {
                return this.nEXTACCOUNTField;
            }
            set {
                this.nEXTACCOUNTField = value;
                this.RaisePropertyChanged("NEXTACCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NEXT-ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string NEXTACCOUNTID {
            get {
                return this.nEXTACCOUNTIDField;
            }
            set {
                this.nEXTACCOUNTIDField = value;
                this.RaisePropertyChanged("NEXTACCOUNTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NEXT-PERIOD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string NEXTPERIOD {
            get {
                return this.nEXTPERIODField;
            }
            set {
                this.nEXTPERIODField = value;
                this.RaisePropertyChanged("NEXTPERIOD");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS")]
    public partial class _EMI : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _ENTITYMASTERINFO _ENTITYMASTERINFOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_ENTITY-MASTER-INFO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public _ENTITYMASTERINFO _ENTITYMASTERINFO {
            get {
                return this._ENTITYMASTERINFOField;
            }
            set {
                this._ENTITYMASTERINFOField = value;
                this.RaisePropertyChanged("_ENTITYMASTERINFO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RTTIE2222", WrapperNamespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS", IsWrapped=true)]
    public partial class RTTIE2222Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
        public CopRevenueGov2.RTTIE222_SrvRef.RTTIE222 RTTIE222;
        
        public RTTIE2222Request() {
        }
        
        public RTTIE2222Request(CopRevenueGov2.RTTIE222_SrvRef.RTTIE222 RTTIE222) {
            this.RTTIE222 = RTTIE222;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RTTIE2222Response", WrapperNamespace="http://ISDEV.city.phila.local/RTTIE222.service:RTTIE222WS", IsWrapped=true)]
    public partial class RTTIE2222Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com-softwareag-entirex-rpc:TIPSACCD")]
        public CopRevenueGov2.RTTIE222_SrvRef.RTTIE222Response RTTIE222Response;
        
        public RTTIE2222Response() {
        }
        
        public RTTIE2222Response(CopRevenueGov2.RTTIE222_SrvRef.RTTIE222Response RTTIE222Response) {
            this.RTTIE222Response = RTTIE222Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RTTIE222WS_PortTypeChannel : CopRevenueGov2.RTTIE222_SrvRef.RTTIE222WS_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RTTIE222WS_PortTypeClient : System.ServiceModel.ClientBase<CopRevenueGov2.RTTIE222_SrvRef.RTTIE222WS_PortType>, CopRevenueGov2.RTTIE222_SrvRef.RTTIE222WS_PortType {
        
        public RTTIE222WS_PortTypeClient() {
        }
        
        public RTTIE222WS_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RTTIE222WS_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RTTIE222WS_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RTTIE222WS_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Response CopRevenueGov2.RTTIE222_SrvRef.RTTIE222WS_PortType.RTTIE2222(CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Request request) {
            return base.Channel.RTTIE2222(request);
        }
        
        public CopRevenueGov2.RTTIE222_SrvRef.RTTIE222Response RTTIE2222(CopRevenueGov2.RTTIE222_SrvRef.RTTIE222 RTTIE222) {
            CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Request inValue = new CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Request();
            inValue.RTTIE222 = RTTIE222;
            CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Response retVal = ((CopRevenueGov2.RTTIE222_SrvRef.RTTIE222WS_PortType)(this)).RTTIE2222(inValue);
            return retVal.RTTIE222Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Response> CopRevenueGov2.RTTIE222_SrvRef.RTTIE222WS_PortType.RTTIE2222Async(CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Request request) {
            return base.Channel.RTTIE2222Async(request);
        }
        
        public System.Threading.Tasks.Task<CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Response> RTTIE2222Async(CopRevenueGov2.RTTIE222_SrvRef.RTTIE222 RTTIE222) {
            CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Request inValue = new CopRevenueGov2.RTTIE222_SrvRef.RTTIE2222Request();
            inValue.RTTIE222 = RTTIE222;
            return ((CopRevenueGov2.RTTIE222_SrvRef.RTTIE222WS_PortType)(this)).RTTIE2222Async(inValue);
        }
    }
}
